# Generated by Django 5.2.4 on 2025-08-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_remove_notificationqs_action_remove_auditqs_auditeur_and_more"),
        ("documentation", "0002_documentpriseencompte"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date_prevue", models.DateField()),
                ("date_realisation", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_faire", "À faire"),
                            ("en_cours", "En cours"),
                            ("fait", "Fait"),
                            ("annule", "Annulé"),
                        ],
                        default="a_faire",
                        max_length=50,
                    ),
                ),
                ("archive", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers un document si l'action est documentaire",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documentation.document",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers une formation si l'action en est une",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action QS",
                "verbose_name_plural": "Actions QS",
            },
        ),
        migrations.CreateModel(
            name="AuditQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_audit", models.DateField()),
                ("type_audit", models.CharField(max_length=100)),
                (
                    "rapport",
                    models.TextField(blank=True, help_text="Résumé du rapport d'audit"),
                ),
                (
                    "auditeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.agent"
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits_recus",
                        to="core.centre",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers le rapport d'audit complet",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documentation.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit QS",
                "verbose_name_plural": "Audits QS",
            },
        ),
        migrations.CreateModel(
            name="EvaluationRisqueQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_evaluation", models.DateField()),
                ("description", models.TextField()),
                (
                    "niveau_risque",
                    models.CharField(
                        help_text="Ex: Acceptable, Tolérable, Inacceptable",
                        max_length=50,
                    ),
                ),
                ("recommandations", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("identifie", "Identifié"),
                            ("evalue", "Évalué"),
                            ("maitrise", "Maîtrisé"),
                            ("clos", "Clos"),
                        ],
                        default="identifie",
                        max_length=50,
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.centre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation de Risque QS",
                "verbose_name_plural": "Évaluations de Risques QS",
            },
        ),
        migrations.CreateModel(
            name="EvenementQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_evenement", models.DateField()),
                ("type_evenement", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "niveau_gravite",
                    models.CharField(
                        help_text="Ex: Mineur, Significatif, Majeur", max_length=50
                    ),
                ),
                (
                    "analyse",
                    models.TextField(
                        blank=True, help_text="Analyse à froid de l'événement"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("analyse", "En analyse"),
                            ("clos", "Clos"),
                        ],
                        default="ouvert",
                        max_length=50,
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.centre"
                    ),
                ),
                (
                    "rapporteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evenements_rapportes_qs",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement QS",
                "verbose_name_plural": "Événements QS",
            },
        ),
        migrations.CreateModel(
            name="NotificationQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destinataire", models.CharField(max_length=255)),
                ("date_envoi", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_envoyer", "À envoyer"),
                            ("envoye", "Envoyé"),
                            ("erreur", "Erreur"),
                        ],
                        default="a_envoyer",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_qs",
                        to="qs.actionqs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification QS",
                "verbose_name_plural": "Notifications QS",
            },
        ),
        migrations.CreateModel(
            name="RecommendationQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priorite",
                    models.CharField(
                        help_text="Ex: Haute, Moyenne, Basse", max_length=50
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("proposee", "Proposée"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                            ("implementee", "Implémentée"),
                        ],
                        default="proposee",
                        max_length=50,
                    ),
                ),
                ("date_emission", models.DateField(auto_now_add=True)),
                ("date_echeance", models.DateField()),
                ("diffusion_nationale", models.BooleanField(default=False)),
                (
                    "centres_cibles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recommandations_qs_cibles",
                        to="core.centre",
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommandations",
                        to="qs.evenementqs",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommandations_qs_responsable",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommandation QS",
                "verbose_name_plural": "Recommandations QS",
            },
        ),
        migrations.AddField(
            model_name="actionqs",
            name="recommendation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions_qs",
                to="qs.recommendationqs",
            ),
        ),
        migrations.CreateModel(
            name="ResponsableQSCentral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsabilite_qs_central",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable QS Central",
                "verbose_name_plural": "Responsables QS Central",
            },
        ),
    ]
