# Generated by Django 5.2.4 on 2025-08-12 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportExterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organisme_source",
                    models.CharField(max_length=255, verbose_name="Organisme Source"),
                ),
                (
                    "reference_externe",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Référence externe"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "fichier_joint",
                    models.FileField(
                        blank=True, null=True, upload_to="qs/rapports_externes/%Y/%m/"
                    ),
                ),
                ("date_reception", models.DateField()),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_externes",
                        to="qs.dossierevenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport Externe",
                "verbose_name_plural": "Rapports Externes",
                "ordering": ["-date_reception"],
            },
        ),
    ]
