# Generated by Django 5.2.4 on 2025-08-12 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qs", "0002_rapportexterne"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriqueFNE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Date et heure effectives de l'événement."
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création du processus d'instruction"),
                            ("DECLARATION_OASIS", "Déclaration OASIS effectuée"),
                            ("COMMENTAIRE", "Commentaire ajouté"),
                            (
                                "CHANGEMENT_STATUT_INSTRUCTION",
                                "Changement d'état de l'instruction",
                            ),
                            ("CLOTURE", "Clôture de la FNE"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Données contextuelles de l'événement (ex: le commentaire, l'ancien/nouveau statut).",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        help_text="Utilisateur à l'origine de l'événement.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_permanent",
                        to="qs.fne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Permanent FNE",
                "verbose_name_plural": "Historiques Permanents FNE",
                "ordering": ["-timestamp"],
            },
        ),
    ]
