# Generated by Django 5.2.3 on 2025-07-20 17:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Centre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_centre",
                    models.CharField(
                        help_text="Nom complet du centre (ex: DGA Essais en vol Istres)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "code_centre",
                    models.CharField(
                        help_text="Code mnémonique du centre (ex: IS, CA, TO)",
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Centre",
                "verbose_name_plural": "Centres",
                "ordering": ["code_centre"],
            },
        ),
        migrations.CreateModel(
            name="Changement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origine",
                    models.TextField(
                        help_text="Qui ou quoi est à l'origine du changement"
                    ),
                ),
                ("description", models.TextField()),
                ("date_creation", models.DateField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("identifie", "Identifié"),
                            ("analyse", "En analyse"),
                            ("approuve", "Approuvé"),
                            ("implemente", "Implémenté"),
                        ],
                        default="identifie",
                        max_length=50,
                    ),
                ),
                (
                    "impact",
                    models.TextField(help_text="Analyse d'impact du changement"),
                ),
                ("archive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Demande de Changement",
                "verbose_name_plural": "Demandes de Changement",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("contact", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Type de Document",
                "verbose_name_plural": "Types de Documents",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id_module",
                    models.IntegerField(
                        help_text="ID legacy du module provenant du CSV",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("module_type", models.CharField(blank=True, max_length=100)),
                ("module", models.CharField(blank=True, max_length=255)),
                ("item", models.CharField(blank=True, max_length=255)),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        db_column="numero",
                        max_length=50,
                        verbose_name="Numéro",
                    ),
                ),
                ("sujet", models.TextField(blank=True)),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Date de la dernière mise à jour du contenu du module",
                        null=True,
                    ),
                ),
                ("validite", models.DateField(blank=True, null=True)),
                ("support", models.CharField(blank=True, max_length=50)),
                (
                    "precisions",
                    models.TextField(blank=True, verbose_name="Sujet / Précisions"),
                ),
            ],
            options={
                "verbose_name": "Module de Formation (Catalogue)",
                "verbose_name_plural": "Modules de Formation (Catalogue)",
            },
        ),
        migrations.CreateModel(
            name="MRR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.CharField(max_length=255)),
                ("date_ouverture", models.DateField(auto_now_add=True)),
                ("date_cloture", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("en_cours", "En cours"),
                            ("clos", "Clos"),
                            ("annule", "Annulé"),
                        ],
                        default="ouvert",
                        max_length=50,
                    ),
                ),
                ("commentaires", models.TextField(blank=True)),
                ("archive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Fiche MRR",
                "verbose_name_plural": "Fiches MRR",
            },
        ),
        migrations.CreateModel(
            name="Organisme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_organisme", models.CharField(max_length=255, unique=True)),
                (
                    "type_organisme",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Interne, ENAC, Partenaire industriel",
                        max_length=100,
                    ),
                ),
                ("agrement", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Organisme de Formation",
                "verbose_name_plural": "Organismes de Formation",
            },
        ),
        migrations.CreateModel(
            name="Parametre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom technique du paramètre",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                ("valeur_defaut", models.CharField(max_length=255)),
                (
                    "type_valeur",
                    models.CharField(
                        choices=[
                            ("string", "Texte"),
                            ("integer", "Entier"),
                            ("boolean", "Booléen"),
                            ("date", "Date"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre",
                "verbose_name_plural": "Paramètres",
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id_agent",
                    models.IntegerField(
                        help_text="ID legacy unique provenant des fichiers CSV",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Référence de l'agent (colonne 'Nom' dans agents.csv, ex: 'BO3')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "trigram",
                    models.CharField(
                        blank=True,
                        help_text="Trigramme unique de l'agent",
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom de famille"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom"),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("nationalite", models.CharField(blank=True, max_length=100)),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'agent est actuellement en service actif",
                    ),
                ),
                (
                    "type_agent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("controleur", "Contrôleur"),
                            ("administratif", "Administratif"),
                            ("technique", "Technique"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur associé",
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="core.centre",
                        verbose_name="Centre de rattachement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "ordering": ["trigram", "reference"],
            },
        ),
        migrations.CreateModel(
            name="Affectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fonction", models.CharField(max_length=255)),
                ("date_debut", models.DateField()),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si l'affectation est en cours",
                        null=True,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="core.agent",
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations_personnel",
                        to="core.centre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation",
                "verbose_name_plural": "Affectations",
            },
        ),
        migrations.CreateModel(
            name="CentreRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.agent"
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.centre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle au sein du Centre",
                "verbose_name_plural": "Rôles au sein des Centres",
            },
        ),
        migrations.CreateModel(
            name="CertificatMed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_visite", models.DateField()),
                (
                    "validite",
                    models.DateField(help_text="Date de fin de validité du certificat"),
                ),
                (
                    "classe",
                    models.CharField(help_text="Ex: Classe 1, Classe 2", max_length=50),
                ),
                ("restriction", models.TextField(blank=True)),
                (
                    "suspension",
                    models.DateField(
                        blank=True,
                        help_text="Date de début de la suspension de l'aptitude",
                        null=True,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificats_medicaux",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificat Médical",
                "verbose_name_plural": "Certificats Médicaux",
                "ordering": ["-validite"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_action", models.CharField(blank=True, max_length=50)),
                (
                    "type_action",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Documentaire, Formation, Technique",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("date_prevue", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_faire", "À faire"),
                            ("en_cours", "En cours"),
                            ("fait", "Fait"),
                            ("annule", "Annulé"),
                        ],
                        default="a_faire",
                        max_length=50,
                    ),
                ),
                ("archive", models.BooleanField(default=False)),
                (
                    "changement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="core.changement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action de Changement",
                "verbose_name_plural": "Actions de Changement",
            },
        ),
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(help_text="Début de la période de délégation."),
                ),
                (
                    "date_fin",
                    models.DateField(help_text="Fin de la période de délégation."),
                ),
                (
                    "motivee_par",
                    models.CharField(
                        blank=True,
                        help_text="Raison de la délégation (ex: Congés, Déplacement).",
                        max_length=255,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "creee_par",
                    models.ForeignKey(
                        help_text="Utilisateur qui a enregistré cette délégation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegations_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegant",
                    models.ForeignKey(
                        help_text="L'agent qui donne ses droits.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_donnees",
                        to="core.agent",
                    ),
                ),
                (
                    "delegataire",
                    models.ForeignKey(
                        help_text="L'agent qui reçoit les droits (l'intérimaire).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_recues",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Délégation de droits",
                "verbose_name_plural": "Délégations de droits",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        help_text="Fichier de la version actuellement en vigueur",
                        upload_to="documents/current/%Y/%m/",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("date_creation", models.DateField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateField(auto_now=True)),
                ("est_archive", models.BooleanField(default=False)),
                (
                    "centres_visibles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Centres pour qui ce document est applicable",
                        related_name="documentation_visible",
                        to="core.centre",
                    ),
                ),
                (
                    "responsable_sms",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_sous_responsabilite",
                        to="core.agent",
                    ),
                ),
                (
                    "type_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.documenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.CreateModel(
            name="AuditQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_audit", models.DateField()),
                ("type_audit", models.CharField(max_length=100)),
                (
                    "rapport",
                    models.TextField(blank=True, help_text="Résumé du rapport d'audit"),
                ),
                (
                    "auditeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.agent"
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits_recus",
                        to="core.centre",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers le rapport d'audit complet",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit QS",
                "verbose_name_plural": "Audits QS",
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_eval",
                    models.CharField(max_length=100, verbose_name="Type d'évaluation"),
                ),
                ("annee", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "resultat",
                    models.CharField(
                        choices=[
                            ("satisfaisant", "Satisfaisant"),
                            ("non_satisfaisant", "Non Satisfaisant"),
                            ("en_cours", "En cours"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
            },
        ),
        migrations.CreateModel(
            name="EvaluationRisqueQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_evaluation", models.DateField()),
                ("description", models.TextField()),
                (
                    "niveau_risque",
                    models.CharField(
                        help_text="Ex: Acceptable, Tolérable, Inacceptable",
                        max_length=50,
                    ),
                ),
                ("recommandations", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("identifie", "Identifié"),
                            ("evalue", "Évalué"),
                            ("maitrise", "Maîtrisé"),
                            ("clos", "Clos"),
                        ],
                        default="identifie",
                        max_length=50,
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.centre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation de Risque QS",
                "verbose_name_plural": "Évaluations de Risques QS",
            },
        ),
        migrations.CreateModel(
            name="EvenementQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_evenement", models.DateField()),
                ("type_evenement", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "niveau_gravite",
                    models.CharField(
                        help_text="Ex: Mineur, Significatif, Majeur", max_length=50
                    ),
                ),
                (
                    "analyse",
                    models.TextField(
                        blank=True, help_text="Analyse à froid de l'événement"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("analyse", "En analyse"),
                            ("clos", "Clos"),
                        ],
                        default="ouvert",
                        max_length=50,
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.centre"
                    ),
                ),
                (
                    "rapporteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evenements_rapportes_qs",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement QS",
                "verbose_name_plural": "Événements QS",
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id_formation",
                    models.IntegerField(
                        help_text="ID legacy de la formation suivie provenant du CSV",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Date précise de la formation", null=True
                    ),
                ),
                (
                    "annee",
                    models.IntegerField(
                        blank=True,
                        help_text="Année de la formation, si la date n'est pas connue",
                        null=True,
                    ),
                ),
                (
                    "duree",
                    models.CharField(
                        blank=True,
                        help_text="Durée en jours, ou texte (ex: 'EPNER')",
                        max_length=20,
                    ),
                ),
                (
                    "resultat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reussi", "Réussi"),
                            ("echoue", "Échoué"),
                            ("en_cours", "En cours"),
                            ("planifie", "Planifié"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formations",
                        to="core.agent",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_formation",
                        to="core.module",
                    ),
                ),
                (
                    "organisme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="formations_dispensees",
                        to="core.organisme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation Suivie",
                "verbose_name_plural": "Formations Suivies",
                "ordering": ["-annee", "-date"],
            },
        ),
        migrations.CreateModel(
            name="ActionQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date_prevue", models.DateField()),
                ("date_realisation", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_faire", "À faire"),
                            ("en_cours", "En cours"),
                            ("fait", "Fait"),
                            ("annule", "Annulé"),
                        ],
                        default="a_faire",
                        max_length=50,
                    ),
                ),
                ("archive", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers un document si l'action est documentaire",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.document",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers une formation si l'action en est une",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action QS",
                "verbose_name_plural": "Actions QS",
            },
        ),
        migrations.CreateModel(
            name="Habilitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_hab",
                    models.CharField(
                        max_length=100, verbose_name="Type d'habilitation"
                    ),
                ),
                ("date_obtention", models.DateField()),
                ("date_expiration", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("valide", "Valide"),
                            ("expiree", "Expirée"),
                            ("revoquee", "Révoquée"),
                        ],
                        default="valide",
                        max_length=50,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habilitations",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habilitation",
                "verbose_name_plural": "Habilitations",
            },
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_licence",
                    models.IntegerField(
                        help_text="ID legacy de la licence provenant du CSV",
                        unique=True,
                    ),
                ),
                ("num_licence", models.CharField(blank=True, max_length=50)),
                ("type_licence", models.CharField(blank=True, max_length=100)),
                ("date_delivrance", models.DateField(blank=True, null=True)),
                (
                    "date_validite",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin de validité"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("valide", "Valide"),
                            ("suspendue", "Suspendue"),
                            ("retiree", "Retirée"),
                            ("expiree", "Expirée"),
                        ],
                        default="valide",
                        max_length=50,
                    ),
                ),
                (
                    "renouvellement",
                    models.DateField(
                        blank=True,
                        help_text="Date du dernier renouvellement",
                        null=True,
                    ),
                ),
                (
                    "suspension",
                    models.DateField(
                        blank=True,
                        help_text="Date de début de la suspension",
                        null=True,
                    ),
                ),
                (
                    "retrait",
                    models.DateField(
                        blank=True, help_text="Date du retrait définitif", null=True
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="Agent détenteur de la licence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licences",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licence",
                "verbose_name_plural": "Licences",
            },
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mention",
                    models.CharField(max_length=100, verbose_name="Type de mention"),
                ),
                ("date_obtention", models.DateField()),
                ("date_validite", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("valide", "Valide"),
                            ("en_cours", "En cours"),
                            ("expiree", "Expirée"),
                        ],
                        default="valide",
                        max_length=50,
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="core.licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mention",
                "verbose_name_plural": "Mentions",
            },
        ),
        migrations.AddField(
            model_name="changement",
            name="mrr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="changements",
                to="core.mrr",
            ),
        ),
        migrations.CreateModel(
            name="MRRProgression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("statut", models.CharField(max_length=100)),
                ("commentaire", models.TextField()),
                (
                    "mrr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progression",
                        to="core.mrr",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progression MRR",
                "verbose_name_plural": "Progressions MRR",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destinataire",
                    models.CharField(
                        help_text="Email ou nom de l'agent/groupe", max_length=255
                    ),
                ),
                ("date_envoi", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_envoyer", "À envoyer"),
                            ("envoye", "Envoyé"),
                            ("erreur", "Erreur"),
                        ],
                        default="a_envoyer",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.CreateModel(
            name="NotificationQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destinataire", models.CharField(max_length=255)),
                ("date_envoi", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_envoyer", "À envoyer"),
                            ("envoye", "Envoyé"),
                            ("erreur", "Erreur"),
                        ],
                        default="a_envoyer",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_qs",
                        to="core.actionqs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification QS",
                "verbose_name_plural": "Notifications QS",
            },
        ),
        migrations.CreateModel(
            name="PositionJour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom court et unique de la position (ex: 'J1', 'Q2', 'RTT', 'MIS')",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description complète (ex: 'Journée normale', 'Mission extérieure')",
                        max_length=255,
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("SITE", "Travail sur site"),
                            ("HORS_SITE", "Travail hors site"),
                            ("NON_TRAVAIL", "Non travail"),
                        ],
                        help_text="Classification de la position pour les statistiques et règles.",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions_jour",
                        to="core.centre",
                        verbose_name="Centre associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position Jour (Planning)",
                "verbose_name_plural": "Positions Jour (Planning)",
                "ordering": ["centre", "nom"],
                "unique_together": {("centre", "nom")},
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_qualif",
                    models.CharField(
                        max_length=100, verbose_name="Type de qualification"
                    ),
                ),
                ("date_obtention", models.DateField()),
                ("date_validite", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("valide", "Valide"),
                            ("en_cours", "En cours de validation"),
                            ("expiree", "Expirée"),
                        ],
                        default="valide",
                        max_length=50,
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="core.licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualification",
                "verbose_name_plural": "Qualifications",
            },
        ),
        migrations.CreateModel(
            name="RecommendationQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priorite",
                    models.CharField(
                        help_text="Ex: Haute, Moyenne, Basse", max_length=50
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("proposee", "Proposée"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                            ("implementee", "Implémentée"),
                        ],
                        default="proposee",
                        max_length=50,
                    ),
                ),
                ("date_emission", models.DateField(auto_now_add=True)),
                ("date_echeance", models.DateField()),
                ("diffusion_nationale", models.BooleanField(default=False)),
                (
                    "centres_cibles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recommandations_qs_cibles",
                        to="core.centre",
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommandations",
                        to="core.evenementqs",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommandations_qs_responsable",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommandation QS",
                "verbose_name_plural": "Recommandations QS",
            },
        ),
        migrations.AddField(
            model_name="actionqs",
            name="recommendation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions_qs",
                to="core.recommendationqs",
            ),
        ),
        migrations.CreateModel(
            name="ResponsableQSCentral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsabilite_qs_central",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable QS Central",
                "verbose_name_plural": "Responsables QS Central",
            },
        ),
        migrations.CreateModel(
            name="ResponsableSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsabilite_sms",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable SMS",
                "verbose_name_plural": "Responsables SMS",
            },
        ),
        migrations.AddField(
            model_name="changement",
            name="responsable_sms",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.responsablesms"
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("CENTRAL", "Central"),
                            ("LOCAL", "Local"),
                            ("OPERATIONNEL", "Opérationnel"),
                        ],
                        default="OPERATIONNEL",
                        max_length=20,
                        verbose_name="Portée du rôle",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("ENCADREMENT", "Encadrement"),
                            ("MANAGEMENT", "Management"),
                            ("EXECUTION", "Exécution"),
                        ],
                        default="EXECUTION",
                        max_length=20,
                        verbose_name="Niveau hiérarchique",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Les ensembles de permissions techniques que ce rôle confère.",
                        to="auth.group",
                        verbose_name="Groupes de permissions associés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle / Fonction Métier",
                "verbose_name_plural": "Rôles / Fonctions Métier",
                "ordering": ["scope", "level", "nom"],
            },
        ),
        migrations.CreateModel(
            name="TourDeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tours_de_service",
                        to="core.agent",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position_apres_midi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affectations_apres_midi",
                        to="core.positionjour",
                    ),
                ),
                (
                    "position_matin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affectations_matin",
                        to="core.positionjour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour de Service",
                "verbose_name_plural": "Tours de Service",
                "ordering": ["-date", "agent"],
                "unique_together": {("agent", "date")},
            },
        ),
        migrations.CreateModel(
            name="TourDeServiceHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("commentaire", models.TextField(blank=True, null=True)),
                ("modifie_le", models.DateTimeField()),
                (
                    "type_modification",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création"),
                            ("MODIFICATION", "Modification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.agent",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historique_tours_modifies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position_apres_midi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.positionjour",
                    ),
                ),
                (
                    "position_matin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.positionjour",
                    ),
                ),
                (
                    "tour_de_service_original",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historique",
                        to="core.tourdeservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de Tour de Service",
                "verbose_name_plural": "Historiques des Tours de Service",
                "ordering": ["-modifie_le"],
            },
        ),
        migrations.CreateModel(
            name="Vol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_demande", models.DateField(auto_now_add=True)),
                ("date_vol", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("realise", "Réalisé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=50,
                    ),
                ),
                (
                    "type_vol",
                    models.CharField(
                        choices=[("CAG", "CAG"), ("CAM", "CAM")], max_length=10
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "cca",
                    models.ForeignKey(
                        help_text="Agent en charge de la coordination du vol (CCA)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vols_en_charge_cca",
                        to="core.agent",
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vols",
                        to="core.centre",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vols",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vol",
                "verbose_name_plural": "Vols",
                "ordering": ["-date_vol", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="ControleVol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heure_prise_en_charge", models.DateTimeField()),
                ("heure_fin_prise_en_charge", models.DateTimeField()),
                (
                    "type_vol",
                    models.CharField(
                        choices=[("CAG", "CAG"), ("CAM", "CAM")],
                        help_text="Type de contrôle réellement effectué",
                        max_length=10,
                    ),
                ),
                (
                    "controleur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vols_controles",
                        to="core.agent",
                    ),
                ),
                (
                    "vol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prises_en_charge",
                        to="core.vol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prise en charge de vol",
                "verbose_name_plural": "Prises en charge de vols",
                "ordering": ["heure_prise_en_charge"],
            },
        ),
        migrations.CreateModel(
            name="AuditHeuresControle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periode",
                    models.CharField(
                        help_text="Format libre, ex: '2024-Q1', '2024-03'",
                        max_length=50,
                    ),
                ),
                ("heures_CAG", models.FloatField(default=0.0)),
                ("heures_CAM", models.FloatField(default=0.0)),
                ("date_audit", models.DateField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits_heures",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit d'heures de contrôle",
                "verbose_name_plural": "Audits d'heures de contrôle",
                "unique_together": {("agent", "periode")},
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_version", models.CharField(max_length=20)),
                ("fichier", models.FileField(upload_to="documents/archives/%Y/%m/")),
                ("date_version", models.DateField()),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Résumé des modifications apportées dans cette version",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version de Document",
                "verbose_name_plural": "Versions de Documents",
                "ordering": ["-date_version"],
                "unique_together": {("document", "numero_version")},
            },
        ),
        migrations.CreateModel(
            name="MRRSignataire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_signature", models.DateField(blank=True, null=True)),
                ("commentaire", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.agent"
                    ),
                ),
                (
                    "mrr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signataires",
                        to="core.mrr",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signataire MRR",
                "verbose_name_plural": "Signataires MRR",
                "unique_together": {("mrr", "agent")},
            },
        ),
        migrations.CreateModel(
            name="AgentRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si l'attribution est à durée indéterminée.",
                        null=True,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_assignes",
                        to="core.agent",
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obligatoire si le rôle est local ou opérationnel.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.centre",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents_assignes",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribution de Rôle",
                "verbose_name_plural": "Attributions de Rôles",
                "unique_together": {("agent", "role", "centre", "date_debut")},
            },
        ),
        migrations.CreateModel(
            name="SignatureCircuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        help_text="Ordre de l'étape dans le circuit (1, 2, 3...)"
                    ),
                ),
                (
                    "organisme",
                    models.CharField(
                        help_text="Entité ou fonction qui doit signer (ex: Chef de centre, Responsable QS)",
                        max_length=255,
                    ),
                ),
                ("date_signature", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("signe", "Signé"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=50,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agent qui a effectivement signé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agent",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circuit_signatures",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de Signature",
                "verbose_name_plural": "Étapes de Signature",
                "ordering": ["document", "ordre"],
                "unique_together": {("document", "ordre")},
            },
        ),
        migrations.CreateModel(
            name="ValeurParametre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.CharField(max_length=255)),
                (
                    "est_global",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez si la valeur s'applique à tous les centres",
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si ce paramètre est spécifique à un centre",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.centre",
                    ),
                ),
                (
                    "parametre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valeurs",
                        to="core.parametre",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        help_text="Agent responsable de cette valeur",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur de Paramètre",
                "verbose_name_plural": "Valeurs de Paramètres",
                "unique_together": {("parametre", "centre")},
            },
        ),
    ]
