# Generated by Django 5.2.3 on 2025-07-21 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionTourDeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee",
                    models.IntegerField(help_text="L'année du planning (ex: 2025)"),
                ),
                (
                    "mois",
                    models.IntegerField(
                        help_text="Le mois du planning (ex: 7 pour Juillet)"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="La date et l'heure exactes de la validation.",
                    ),
                ),
                (
                    "donnees_planning",
                    models.JSONField(
                        help_text="Snapshot complet du planning au moment de la validation."
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions_planning",
                        to="core.centre",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        help_text="L'utilisateur qui a validé cette version.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Version Validée de Tour de Service",
                "verbose_name_plural": "Versions Validées de Tour de Service",
                "ordering": ["-annee", "-mois", "-date_validation"],
                "unique_together": {("centre", "annee", "mois")},
            },
        ),
    ]
