# Generated by Django 5.2.4 on 2025-08-19 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificatmed",
            options={
                "ordering": ["-date_visite"],
                "verbose_name": "Certificat Médical",
                "verbose_name_plural": "Certificats Médicaux",
            },
        ),
        migrations.RemoveField(
            model_name="certificatmed",
            name="classe",
        ),
        migrations.RemoveField(
            model_name="certificatmed",
            name="restriction",
        ),
        migrations.RemoveField(
            model_name="certificatmed",
            name="suspension",
        ),
        migrations.RemoveField(
            model_name="certificatmed",
            name="validite",
        ),
        migrations.AddField(
            model_name="certificatmed",
            name="classe_aptitude",
            field=models.CharField(
                choices=[("CLASSE_3", "Classe 3")], default="CLASSE_3", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="certificatmed",
            name="commentaire",
            field=models.TextField(blank=True, verbose_name="Commentaire"),
        ),
        migrations.AddField(
            model_name="certificatmed",
            name="date_expiration_aptitude",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'expiration de l'aptitude"
            ),
        ),
        migrations.AddField(
            model_name="certificatmed",
            name="organisme_medical",
            field=models.CharField(
                default="Information non disponible",
                max_length=255,
                verbose_name="Centre médical",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="certificatmed",
            name="restrictions",
            field=models.TextField(
                blank=True, help_text="Ex: Port de verres correcteurs obligatoire."
            ),
        ),
        migrations.AddField(
            model_name="certificatmed",
            name="resultat",
            field=models.CharField(
                choices=[
                    ("APTE", "Apte"),
                    ("INAPTE_TEMP", "Inapte Temporaire"),
                    ("INAPTE_DEF", "Inapte Définitif"),
                ],
                default="Information non disponible",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="certificatmed",
            name="date_visite",
            field=models.DateField(verbose_name="Date de la visite"),
        ),
        migrations.CreateModel(
            name="RendezVousMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_heure_rdv",
                    models.DateTimeField(verbose_name="Date et heure du rendez-vous"),
                ),
                (
                    "organisme_medical",
                    models.CharField(max_length=255, verbose_name="Centre médical"),
                ),
                (
                    "type_visite",
                    models.CharField(
                        default="Visite périodique Classe 3", max_length=100
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIE", "Planifié"),
                            ("REALISE", "Réalisé"),
                            ("ANNULE", "Annulé"),
                            ("REPORTE", "Reporté"),
                        ],
                        default="PLANIFIE",
                        max_length=20,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendez_vous_medicaux",
                        to="core.agent",
                    ),
                ),
                (
                    "certificat_genere",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.certificatmed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-vous Médical",
                "verbose_name_plural": "Rendez-vous Médicaux",
                "ordering": ["-date_heure_rdv"],
            },
        ),
    ]
