# Generated by Django 5.2.4 on 2025-09-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeActiviteHorsVol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                (
                    "couleur_affichage",
                    models.CharField(
                        default="#CCCCCC",
                        help_text="Code couleur Hex (ex: #CCCCCC)",
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="centre",
            name="sous_gestion_cca",
            field=models.BooleanField(
                default=False,
                help_text="Cocher si la planification de ce centre est gérée par la CCA.",
                verbose_name="Sous gestion CCA",
            ),
        ),
        migrations.CreateModel(
            name="IndisponibiliteCabine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_cabine",
                    models.CharField(
                        help_text="Ex: 'Cabine 1', 'Position TOUR'", max_length=100
                    ),
                ),
                ("date_jour", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("motif", models.CharField(blank=True, max_length=255)),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indisponibilites_cabines",
                        to="core.centre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indisponibilité de Cabine",
                "verbose_name_plural": "Indisponibilités de Cabines",
            },
        ),
    ]
