# Generated by Django 5.2.4 on 2025-08-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="nom",
            field=models.CharField(
                choices=[
                    ("ADJOINT_CHEF_DE_CENTRE", "Adjoint Chef de Centre"),
                    ("ADJOINT_CHEF_DE_DIVISION", "Adjoint Chef de Division"),
                    ("ADJOINT_ES", "Adjoint ES"),
                    ("ADJOINT_FORM", "Adjoint Form"),
                    ("ADJOINT_QS", "Adjoint QS"),
                    ("ADJOINT_SMSI", "Adjoint SMSI"),
                    ("CHEF_DE_CENTRE", "Chef de Centre"),
                    ("CHEF_DE_DIVISION", "Chef de Division"),
                    ("CHEF_DE_QUART", "Chef de Quart"),
                    ("CONTROLEUR", "Contrôleur"),
                    ("FORM_LOCAL", "Formateur Local"),
                    ("QS_LOCAL", "QS Local"),
                    ("RESPONSABLE_SMS", "Responsable SMS"),
                    ("SMS_LOCAL", "SMS Local"),
                    ("ES_LOCAL", "ES Local"),
                    ("SMSI_LOCAL", "SMSI Local"),
                    ("ADJOINT_CONFORMITE", "Adjoint Conformité"),
                    ("COORDONATEUR", "Coordonnateur"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Nom du Rôle",
            ),
        ),
    ]
