# Generated by Django 5.2.3 on 2025-07-21 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_versiontourdeservice"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="versiontourdeservice",
            unique_together=set(),
        ),
    ]
