# Generated by Django 5.2.3 on 2025-07-06 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0002_agent_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["scope", "level", "nom"],
                "verbose_name": "Rôle / Fonction Métier",
                "verbose_name_plural": "Rôles / Fonctions Métier",
            },
        ),
        migrations.AlterUniqueTogether(
            name="agentrole",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="agentrole",
            name="date_debut",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date de début"
            ),
        ),
        migrations.AddField(
            model_name="agentrole",
            name="date_fin",
            field=models.DateField(
                blank=True,
                help_text="Laisser vide si l'attribution est à durée indéterminée.",
                null=True,
                verbose_name="Date de fin",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Les ensembles de permissions techniques que ce rôle confère.",
                to="auth.group",
                verbose_name="Groupes de permissions associés",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="level",
            field=models.CharField(
                choices=[
                    ("ENCADREMENT", "Encadrement"),
                    ("MANAGEMENT", "Management"),
                    ("EXECUTION", "Exécution"),
                ],
                default="EXECUTION",
                max_length=20,
                verbose_name="Niveau hiérarchique",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="scope",
            field=models.CharField(
                choices=[
                    ("CENTRAL", "Central"),
                    ("LOCAL", "Local"),
                    ("OPERATIONNEL", "Opérationnel"),
                ],
                default="OPERATIONNEL",
                max_length=20,
                verbose_name="Portée du rôle",
            ),
        ),
        migrations.AlterField(
            model_name="agentrole",
            name="centre",
            field=models.ForeignKey(
                blank=True,
                help_text="Obligatoire si le rôle est local ou opérationnel.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.centre",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentrole",
            unique_together={("agent", "role", "centre", "date_debut")},
        ),
    ]
