# Generated by Django 5.2.4 on 2025-08-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_certificatmed_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatmed",
            name="piece_jointe",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="certificats_medicaux/%Y/%m/",
                verbose_name="Scan du certificat (optionnel)",
            ),
        ),
    ]
