# Generated by Django 5.2.4 on 2025-08-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="level",
            field=models.CharField(
                choices=[
                    ("ENCADREMENT", "Encadrement"),
                    ("MANAGEMENT", "Management"),
                    ("EXECUTION", "Exécution"),
                ],
                max_length=20,
                verbose_name="Niveau hiérarchique",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="nom",
            field=models.CharField(
                choices=[
                    ("ADJOINT_CHEF_DE_CENTRE", "Adjoint Chef de Centre"),
                    ("ADJOINT_CHEF_DE_DIVISION", "Adjoint Chef de Division"),
                    ("ADJOINT_ES", "Adjoint ES"),
                    ("ADJOINT_FORM", "Adjoint Form"),
                    ("ADJOINT_QS", "Adjoint QS"),
                    ("CHEF_DE_CENTRE", "Chef de Centre"),
                    ("CHEF_DE_DIVISION", "Chef de Division"),
                    ("CHEF_DE_QUART", "Chef de Quart"),
                    ("CONTROLEUR", "Contrôleur"),
                    ("FORM_LOCAL", "Formateur Local"),
                    ("QS_LOCAL", "QS Local"),
                    ("RESPONSABLE_SMS", "Responsable SMS"),
                    ("SMS_LOCAL", "SMS Local"),
                    ("ES_LOCAL", "ES Local"),
                    ("ADJOINT_CONFORMITE", "Adjoint Conformité"),
                    ("COORDONATEUR", "Coordonnateur"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Nom du Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="scope",
            field=models.CharField(
                choices=[
                    ("CENTRAL", "Central"),
                    ("LOCAL", "Local"),
                    ("OPERATIONNEL", "Opérationnel"),
                ],
                max_length=20,
                verbose_name="Portée du rôle",
            ),
        ),
    ]
