# Generated by Django 5.2.4 on 2025-08-12 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationqs",
            name="action",
        ),
        migrations.RemoveField(
            model_name="auditqs",
            name="auditeur",
        ),
        migrations.RemoveField(
            model_name="auditqs",
            name="centre",
        ),
        migrations.RemoveField(
            model_name="auditqs",
            name="document",
        ),
        migrations.RemoveField(
            model_name="evaluationrisqueqs",
            name="centre",
        ),
        migrations.RemoveField(
            model_name="evenementqs",
            name="centre",
        ),
        migrations.RemoveField(
            model_name="evenementqs",
            name="rapporteur",
        ),
        migrations.RemoveField(
            model_name="recommendationqs",
            name="evenement",
        ),
        migrations.RemoveField(
            model_name="recommendationqs",
            name="centres_cibles",
        ),
        migrations.RemoveField(
            model_name="recommendationqs",
            name="responsable",
        ),
        migrations.RemoveField(
            model_name="responsableqscentral",
            name="agent",
        ),
        migrations.DeleteModel(
            name="ActionQS",
        ),
        migrations.DeleteModel(
            name="NotificationQS",
        ),
        migrations.DeleteModel(
            name="AuditQS",
        ),
        migrations.DeleteModel(
            name="EvaluationRisqueQS",
        ),
        migrations.DeleteModel(
            name="EvenementQS",
        ),
        migrations.DeleteModel(
            name="RecommendationQS",
        ),
        migrations.DeleteModel(
            name="ResponsableQSCentral",
        ),
    ]
