# Generated by Django 5.2.4 on 2025-10-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_typeactivitehorsvol_centre_sous_gestion_cca_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentreMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: CMPA Aix-en-Provence",
                        max_length=200,
                        unique=True,
                        verbose_name="Nom du centre",
                    ),
                ),
                (
                    "type_centre",
                    models.CharField(
                        choices=[
                            ("CMPA", "Centre Médical des Personnels Aériens"),
                            ("HIA", "Hôpital d'Instruction des Armées"),
                            ("CIVIL", "Centre médical civil agréé"),
                        ],
                        default="CMPA",
                        max_length=20,
                    ),
                ),
                (
                    "adresse",
                    models.TextField(blank=True, verbose_name="Adresse complète"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de contact"
                    ),
                ),
                (
                    "contact_referent",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Dr DUPONT - Service médecine aéronautique",
                        max_length=100,
                        verbose_name="Contact référent",
                    ),
                ),
                (
                    "delai_moyen_rdv_jours",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Délai habituel pour obtenir un rendez-vous",
                        verbose_name="Délai moyen RDV (jours)",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Décocher pour désactiver sans supprimer",
                        verbose_name="Centre actif",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Informations pratiques, horaires, etc.",
                        verbose_name="Notes",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Centre Médical",
                "verbose_name_plural": "Centres Médicaux",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="ArretMaladie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "date_fin_prevue",
                    models.DateField(verbose_name="Date de fin prévue"),
                ),
                (
                    "date_fin_reelle",
                    models.DateField(
                        blank=True,
                        help_text="Remplir lors du retour effectif de l'agent",
                        null=True,
                        verbose_name="Date de fin réelle",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Grippe, Post-opératoire, etc.",
                        max_length=200,
                        verbose_name="Motif (optionnel)",
                    ),
                ),
                (
                    "certificat_arret",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="arrets_maladie/%Y/%m/",
                        verbose_name="Certificat médical (optionnel)",
                    ),
                ),
                (
                    "visite_reprise_requise",
                    models.BooleanField(
                        default=False,
                        help_text="Automatique si > 21 jours",
                        verbose_name="Visite de reprise requise",
                    ),
                ),
                (
                    "visite_reprise_effectuee",
                    models.BooleanField(
                        default=False, verbose_name="Visite de reprise effectuée"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de saisie"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrets_maladie",
                        to="core.agent",
                        verbose_name="Agent concerné",
                    ),
                ),
                (
                    "rdv_reprise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arrets_lies",
                        to="core.rendezvousmedical",
                        verbose_name="RDV de reprise lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arrêt Maladie",
                "verbose_name_plural": "Arrêts Maladie",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Avertissement"),
                            ("ALERT", "Alerte"),
                            ("SUCCESS", "Succès"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "lue",
                    models.BooleanField(default=False, verbose_name="Notification lue"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_lecture", models.DateTimeField(blank=True, null=True)),
                (
                    "lien_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="URL de redirection"
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.agent",
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["destinataire", "-date_creation"],
                        name="core_notifi_destina_8bb365_idx",
                    ),
                    models.Index(
                        fields=["destinataire", "lue"],
                        name="core_notifi_destina_7c8e7b_idx",
                    ),
                ],
            },
        ),
    ]
