# Generated by Django 5.2.3 on 2025-07-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_versiontourdeservice_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="versiontourdeservice",
            name="numero_version",
            field=models.CharField(
                default="",
                editable=False,
                help_text="Identifiant unique de la version (ex: 072025-1)",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
