# Generated by Django 5.2.3 on 2025-07-06 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_role_options_alter_agentrole_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(help_text="Début de la période de délégation."),
                ),
                (
                    "date_fin",
                    models.DateField(help_text="Fin de la période de délégation."),
                ),
                (
                    "motivee_par",
                    models.CharField(
                        blank=True,
                        help_text="Raison de la délégation (ex: Congés, Déplacement).",
                        max_length=255,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "creee_par",
                    models.ForeignKey(
                        help_text="Utilisateur qui a enregistré cette délégation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegations_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegant",
                    models.ForeignKey(
                        help_text="L'agent qui donne ses droits.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_donnees",
                        to="core.agent",
                    ),
                ),
                (
                    "delegataire",
                    models.ForeignKey(
                        help_text="L'agent qui reçoit les droits (l'intérimaire).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_recues",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Délégation de droits",
                "verbose_name_plural": "Délégations de droits",
                "ordering": ["-date_debut"],
            },
        ),
    ]
