# Generated by Django 5.2.4 on 2025-10-16 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_centremedical_arretmaladie_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatmed",
            name="date_saisie",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date de saisie"
            ),
        ),
        migrations.AddField(
            model_name="certificatmed",
            name="saisi_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificats_saisis",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Saisi par",
            ),
        ),
        migrations.AddField(
            model_name="rendezvousmedical",
            name="commentaire",
            field=models.TextField(blank=True, verbose_name="Commentaire"),
        ),
        migrations.AddField(
            model_name="rendezvousmedical",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rdv_crees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="rendezvousmedical",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date de création"
            ),
        ),
        migrations.AddField(
            model_name="rendezvousmedical",
            name="date_modification",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AddField(
            model_name="rendezvousmedical",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rdv_modifies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.CreateModel(
            name="HistoriqueRDV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création"),
                            ("MODIFICATION", "Modification"),
                            ("ANNULATION", "Annulation"),
                            ("REALISATION", "Réalisation"),
                        ],
                        max_length=20,
                        verbose_name="Type d'action",
                    ),
                ),
                (
                    "date_action",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de l'action"
                    ),
                ),
                (
                    "ancien_statut",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Ancien statut"
                    ),
                ),
                (
                    "nouveau_statut",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Nouveau statut"
                    ),
                ),
                (
                    "ancienne_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ancienne date RDV"
                    ),
                ),
                (
                    "nouvelle_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Nouvelle date RDV"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "rdv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="core.rendezvousmedical",
                        verbose_name="Rendez-vous concerné",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_rdv",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique RDV",
                "verbose_name_plural": "Historiques RDV",
                "ordering": ["-date_action"],
            },
        ),
    ]
