# Generated by Django 5.2.4 on 2025-08-06 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_role_level_alter_role_nom_alter_role_scope"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delegation",
            options={
                "ordering": ["-date_debut"],
                "verbose_name": "Délégation de Rôle",
                "verbose_name_plural": "Délégations de Rôles",
            },
        ),
        migrations.AddField(
            model_name="delegation",
            name="agent_role_delegue",
            field=models.ForeignKey(
                help_text="L'assignation de rôle qui est temporairement prêtée.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delegations",
                to="core.agentrole",
            ),
        ),
    ]
