# Generated by Django 5.2.3 on 2025-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_versiontourdeservice_numero_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionjour",
            name="couleur",
            field=models.CharField(
                default="#FFFFFF",
                help_text="Code couleur hexadécimal (ex: #4169E1). Le blanc est la couleur par défaut.",
                max_length=7,
            ),
        ),
    ]
