# Generated by Django 5.2.3 on 2025-07-24 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_positionjour_couleur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeuilleTempsVerrou",
            fields=[
                (
                    "centre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="verrou_feuille_temps",
                        serialize=False,
                        to="core.centre",
                    ),
                ),
                ("verrouille_a", models.DateTimeField(auto_now_add=True)),
                (
                    "chef_de_quart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.agent"
                    ),
                ),
            ],
            options={
                "verbose_name": "Verrou d'édition de Feuille de Temps",
            },
        ),
        migrations.CreateModel(
            name="FeuilleTempsEntree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_jour", models.DateField(db_index=True)),
                ("heure_arrivee", models.TimeField(blank=True, null=True)),
                ("heure_depart", models.TimeField(blank=True, null=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pointages",
                        to="core.agent",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée de Feuille de Temps",
                "ordering": ["-date_jour", "agent"],
                "permissions": [
                    ("view_feuilletemps", "Peut voir la feuille de temps journalière"),
                    (
                        "change_feuilletemps",
                        "Peut modifier la feuille de temps journalière",
                    ),
                ],
                "unique_together": {("agent", "date_jour")},
            },
        ),
    ]
