# Generated by Django 5.2.4 on 2025-10-17 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_arretmaladie_enhancements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arretmaladie",
            name="cloture_par",
        ),
        migrations.RemoveField(
            model_name="arretmaladie",
            name="date_cloture",
        ),
        migrations.RemoveField(
            model_name="arretmaladie",
            name="statut",
        ),
    ]
