# Generated by Django 5.2.3 on 2025-07-24 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_feuilletempsverrou_feuilletempsentree"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeuilleTempsCloture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_jour", models.DateField()),
                ("cloture_le", models.DateTimeField(auto_now_add=True)),
                ("reouverte_le", models.DateTimeField(blank=True, null=True)),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.centre"
                    ),
                ),
                (
                    "cloture_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journees_cloturees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reouverte_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journees_reouvertes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journée de Pointage Clôturée",
                "permissions": [
                    (
                        "reouvrir_feuilletemps",
                        "Peut rouvrir une journée de pointage clôturée",
                    )
                ],
                "unique_together": {("centre", "date_jour")},
            },
        ),
    ]
