# Generated by Django 5.2.4 on 2025-10-18 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_arretmaladie_cloture_par_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="arretmaladie",
            name="cloture_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="arrets_clotures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Clôturé par",
            ),
        ),
        migrations.AddField(
            model_name="arretmaladie",
            name="date_cloture",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de déclaration de reprise ou d'annulation",
                null=True,
                verbose_name="Date de clôture",
            ),
        ),
        migrations.AddField(
            model_name="arretmaladie",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_COURS", "En cours"),
                    ("CLOTURE", "Clôturé (reprise effectuée)"),
                    ("ANNULE", "Annulé"),
                ],
                default="EN_COURS",
                max_length=20,
                verbose_name="Statut de l'arrêt",
            ),
        ),
    ]
