# Generated by Django 5.2.4 on 2025-10-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_positionjour_categorie"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tourdeservice",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="tourdeservice",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tours_de_service",
                to="core.agent",
            ),
        ),
    ]
