# Generated by Django 5.2.3 on 2025-07-25 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_feuilletempsentree_options_categorieevenement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceJournalier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_jour", models.DateField(db_index=True)),
                ("heure_ouverture", models.TimeField(verbose_name="Heure d'ouverture")),
                (
                    "heure_cloture",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de clôture"
                    ),
                ),
                (
                    "date_visa",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date du visa"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("OUVERTE", "Ouverte"),
                            ("CLOTUREE", "Clôturée"),
                            ("VISEE", "Visée"),
                        ],
                        default="OUVERTE",
                        max_length=10,
                    ),
                ),
                (
                    "cdq_cloture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services_clotures",
                        to="core.agent",
                        verbose_name="CDQ de clôture",
                    ),
                ),
                (
                    "cdq_ouverture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services_ouverts",
                        to="core.agent",
                        verbose_name="CDQ d'ouverture",
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services_journaliers",
                        to="core.centre",
                    ),
                ),
                (
                    "cloture_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journees_cloturees_trace",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ouvert_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journees_initialisees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vise_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services_vises",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Visé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Journalier",
                "verbose_name_plural": "Services Journaliers",
                "ordering": ["-date_jour", "centre"],
                "permissions": [
                    (
                        "open_close_service",
                        "Peut ouvrir et clôturer le service journalier",
                    ),
                    ("visa_service", "Peut viser un service journalier clôturé"),
                ],
                "unique_together": {("centre", "date_jour")},
            },
        ),
    ]
