# Generated by Django 5.2.3 on 2025-07-26 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_servicejournalier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicejournalier",
            options={
                "ordering": ["-date_jour", "centre"],
                "permissions": [
                    (
                        "open_close_service",
                        "Peut ouvrir et clôturer le service journalier",
                    ),
                    ("visa_service", "Peut viser un service journalier clôturé"),
                    ("reopen_service", "Peut rouvrir un service journalier clôturé"),
                ],
                "verbose_name": "Service Journalier",
                "verbose_name_plural": "Services Journaliers",
            },
        ),
    ]
