# Generated by Django 5.2.3 on 2025-07-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_servicejournalier_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicejournalier",
            options={
                "ordering": ["-date_jour", "centre"],
                "permissions": [
                    (
                        "open_close_service",
                        "Peut ouvrir et clôturer le service journalier",
                    ),
                    ("visa_service", "Peut viser un service journalier clôturé"),
                ],
                "verbose_name": "Service Journalier",
                "verbose_name_plural": "Services Journaliers",
            },
        ),
        migrations.CreateModel(
            name="ServiceJournalierHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("OUVERTURE", "Ouverture du service"),
                            ("CLOTURE", "Clôture du service"),
                            ("REOUVERTURE", "Réouverture du service"),
                            ("VISA", "Visa du service"),
                        ],
                        max_length=20,
                        verbose_name="Action effectuée",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date et heure de l'action"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Détails ou justification de l'action (ex: raison de la réouverture).",
                    ),
                ),
                (
                    "effectuee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Effectuée par",
                    ),
                ),
                (
                    "service_journalier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="core.servicejournalier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique du Service Journalier",
                "verbose_name_plural": "Historiques des Services Journaliers",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="FeuilleTempsCloture",
        ),
    ]
