# Generated by Django 5.2.3 on 2025-07-26 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_servicejournalier_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicejournalier",
            options={
                "ordering": ["-date_jour", "centre"],
                "permissions": [
                    (
                        "open_close_service",
                        "Peut ouvrir et clôturer le service journalier",
                    ),
                    ("visa_service", "Peut viser un service journalier clôturé"),
                    ("reopen_service", "Peut rouvrir un service journalier clôturé"),
                ],
                "verbose_name": "Service Journalier",
                "verbose_name_plural": "Services Journaliers",
            },
        ),
        migrations.RemoveField(
            model_name="servicejournalierhistorique",
            name="action",
        ),
        migrations.RemoveField(
            model_name="servicejournalierhistorique",
            name="details",
        ),
        migrations.RemoveField(
            model_name="servicejournalierhistorique",
            name="effectuee_par",
        ),
        migrations.AddField(
            model_name="servicejournalierhistorique",
            name="agent_action",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.agent",
                verbose_name="Agent",
            ),
        ),
        migrations.AddField(
            model_name="servicejournalierhistorique",
            name="modifie_par",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="servicejournalierhistorique",
            name="type_action",
            field=models.CharField(
                choices=[
                    ("OUVERTURE", "Ouverture"),
                    ("CLOTURE", "Clôture"),
                    ("REOUVERTURE", "Réouverture"),
                ],
                default="OUVERTURE",
                max_length=20,
                verbose_name="Type d'action",
            ),
        ),
        migrations.AlterField(
            model_name="servicejournalierhistorique",
            name="service_journalier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historique",
                to="core.servicejournalier",
            ),
        ),
        migrations.AlterField(
            model_name="servicejournalierhistorique",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
        ),
    ]
