# Generated by Django 5.2.3 on 2025-07-27 19:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_servicejournalier_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom court et clair de la zone.", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description plus détaillée de la zone et de ses limites ou fonctions.",
                    ),
                ),
                (
                    "est_active",
                    models.BooleanField(
                        default=False, verbose_name="Actuellement active"
                    ),
                ),
                (
                    "derniere_activite",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière activité"
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        help_text="Le centre auquel cette zone est rattachée.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="core.centre",
                    ),
                ),
                (
                    "dernier_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zones_modifiees",
                        to="core.agent",
                        verbose_name="Dernier agent intervenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "ordering": ["centre", "nom"],
                "unique_together": {("centre", "nom")},
            },
        ),
        migrations.CreateModel(
            name="ActiviteZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_action",
                    models.CharField(
                        choices=[
                            ("ACTIVATION", "Activation"),
                            ("DESACTIVATION", "Désactivation"),
                        ],
                        max_length=20,
                        verbose_name="Type d'action",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Horodatage de l'action",
                    ),
                ),
                (
                    "agent_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.agent",
                        verbose_name="Agent ayant effectué l'action",
                    ),
                ),
                (
                    "service_journalier",
                    models.ForeignKey(
                        help_text="Lie l'activité au service journalier qui était ouvert.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activites_zone_du_jour",
                        to="core.servicejournalier",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_activites",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité de Zone",
                "verbose_name_plural": "Activités des Zones",
                "ordering": ["-timestamp"],
            },
        ),
    ]
