# Generated by Django 5.2.4 on 2025-08-15 21:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_alter_role_nom"),
        ("documentation", "0001_initial"),
        ("technique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "centre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smsi",
                        to="core.centre",
                    ),
                ),
                (
                    "manuel_management",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers le Manuel de Management de la Sécurité de l'Information.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documentation.document",
                    ),
                ),
                (
                    "programme_surete",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers le Programme de Sûreté.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documentation.document",
                    ),
                ),
                (
                    "relais_local",
                    models.ForeignKey(
                        help_text="Relais SMSI désigné pour ce centre (rôle SMSI_LOCAL).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smsi_pilotes_locaux",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier de Conformité SMSI",
                "verbose_name_plural": "Dossiers de Conformité SMSI",
            },
        ),
        migrations.CreateModel(
            name="CyberRisque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description du risque")),
                (
                    "gravite",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYENNE", "Moyenne"),
                            ("ELEVEE", "Élevée"),
                            ("CRITIQUE", "Critique"),
                        ],
                        default="MOYENNE",
                        max_length=20,
                    ),
                ),
                (
                    "probabilite",
                    models.CharField(
                        choices=[
                            ("TRES_FAIBLE", "Très Faible"),
                            ("FAIBLE", "Faible"),
                            ("MOYENNE", "Moyenne"),
                            ("ELEVEE", "Élevée"),
                        ],
                        default="MOYENNE",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("OUVERT", "Ouvert (en attente de traitement)"),
                            ("TRAITE", "Traité (mesures appliquées)"),
                            ("ACCEPTE", "Accepté (risque résiduel assumé)"),
                            ("REFUSE", "Refusé (activité évitée)"),
                        ],
                        default="OUVERT",
                        max_length=20,
                    ),
                ),
                (
                    "smsi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risques",
                        to="cyber.smsi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risque de Cybersécurité",
                "verbose_name_plural": "Registre des Risques de Cybersécurité",
                "ordering": ["statut", "-gravite"],
            },
        ),
        migrations.CreateModel(
            name="CyberIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date et heure de l'incident",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de l'incident"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DETECTION", "Détection (en attente de qualification)"),
                            ("ANALYSE", "Analyse en cours"),
                            ("REMEDIATION", "Remédiation en cours"),
                            ("RESOLU", "Résolu"),
                            ("CLOTURE", "Clôturé (retour d'expérience effectué)"),
                        ],
                        default="DETECTION",
                        max_length=20,
                    ),
                ),
                (
                    "source_panne",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers la panne technique d'origine, si applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_cyber_associes",
                        to="technique.pannecentre",
                    ),
                ),
                (
                    "smsi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="cyber.smsi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident de Cybersécurité",
                "verbose_name_plural": "Registre des Incidents de Cybersécurité",
                "ordering": ["-date"],
            },
        ),
    ]
