# Generated by Django 5.2.4 on 2025-08-20 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        ("documentation", "0001_initial"),
        ("technique", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CyberRisque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description du risque")),
                (
                    "gravite",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYENNE", "Moyenne"),
                            ("ELEVEE", "Élevée"),
                            ("CRITIQUE", "Critique"),
                        ],
                        default="MOYENNE",
                        max_length=20,
                    ),
                ),
                (
                    "probabilite",
                    models.CharField(
                        choices=[
                            ("TRES_FAIBLE", "Très Faible"),
                            ("FAIBLE", "Faible"),
                            ("MOYENNE", "Moyenne"),
                            ("ELEVEE", "Élevée"),
                        ],
                        default="MOYENNE",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("OUVERT", "Ouvert (en attente de traitement)"),
                            ("TRAITE", "Traité (mesures appliquées)"),
                            ("ACCEPTE", "Accepté (risque résiduel assumé)"),
                            ("REFUSE", "Refusé (activité évitée)"),
                        ],
                        default="OUVERT",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risque de Cybersécurité",
                "verbose_name_plural": "Registre des Risques de Cybersécurité",
                "ordering": ["statut", "-gravite"],
            },
        ),
        migrations.CreateModel(
            name="CyberIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date et heure de l'incident",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de l'incident"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DETECTION", "Détection (en attente de qualification)"),
                            ("ANALYSE", "Analyse en cours"),
                            ("REMEDIATION", "Remédiation en cours"),
                            ("RESOLU", "Résolu"),
                            ("CLOTURE", "Clôturé (retour d'expérience effectué)"),
                        ],
                        default="DETECTION",
                        max_length=20,
                    ),
                ),
                (
                    "source_panne",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers la panne technique d'origine, si applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_cyber_associes",
                        to="technique.pannecentre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident de Cybersécurité",
                "verbose_name_plural": "Registre des Incidents de Cybersécurité",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CyberIncidentHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création de l'incident"),
                            ("CHANGEMENT_STATUT", "Changement de statut"),
                            ("QUALIFICATION", "Qualification depuis une panne"),
                            ("COMMENTAIRE", "Commentaire ajouté"),
                            ("RESOLUTION", "Incident résolu"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="cyber.cyberincident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'Incident Cyber",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CyberRisqueHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création du risque"),
                            ("CHANGEMENT_STATUT", "Changement de statut"),
                            ("MODIFICATION", "Modification des détails"),
                            ("COMMENTAIRE", "Commentaire ajouté"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="cyber.cyberrisque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de Risque Cyber",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PieceJointe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.FileField(upload_to="cyber/pieces_jointes/%Y/%m/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce Jointe",
                "verbose_name_plural": "Pièces Jointes",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "centre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smsi",
                        to="core.centre",
                    ),
                ),
                (
                    "manuel_management",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers le Manuel de Management de la Sécurité de l'Information.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documentation.document",
                    ),
                ),
                (
                    "programme_surete",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lien vers le Programme de Sûreté.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documentation.document",
                    ),
                ),
                (
                    "relais_local",
                    models.ForeignKey(
                        help_text="Relais SMSI désigné pour ce centre (rôle SMSI_LOCAL).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smsi_pilotes_locaux",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier de Conformité SMSI",
                "verbose_name_plural": "Dossiers de Conformité SMSI",
            },
        ),
        migrations.AddField(
            model_name="cyberrisque",
            name="smsi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risques",
                to="cyber.smsi",
            ),
        ),
        migrations.AddField(
            model_name="cyberincident",
            name="smsi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="cyber.smsi",
            ),
        ),
    ]
