# Generated by Django 5.2.4 on 2025-08-15 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyber", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CyberIncidentHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création de l'incident"),
                            ("CHANGEMENT_STATUT", "Changement de statut"),
                            ("QUALIFICATION", "Qualification depuis une panne"),
                            ("COMMENTAIRE", "Commentaire ajouté"),
                            ("RESOLUTION", "Incident résolu"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="cyber.cyberincident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'Incident Cyber",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CyberRisqueHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création du risque"),
                            ("CHANGEMENT_STATUT", "Changement de statut"),
                            ("MODIFICATION", "Modification des détails"),
                            ("COMMENTAIRE", "Commentaire ajouté"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="cyber.cyberrisque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de Risque Cyber",
                "ordering": ["-timestamp"],
            },
        ),
    ]
