# Generated by Django 5.2.4 on 2025-08-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brevet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_brevet",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Numéro de Brevet"
                    ),
                ),
                ("date_delivrance", models.DateField()),
            ],
            options={
                "verbose_name": "Brevet de contrôleur",
                "verbose_name_plural": "Brevets des contrôleurs",
                "permissions": [
                    (
                        "view_all_brevets",
                        "Peut voir les dossiers de compétences de tous les agents",
                    ),
                    (
                        "view_centre_brevets",
                        "Peut voir les dossiers de compétences des agents de son centre",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvenementCarriere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("SUSPENSION_MANUELLE", "Suspension Manuelle de MUA"),
                            ("REPRISE_ACTIVITE", "Reprise d'activité"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "details",
                    models.TextField(
                        help_text="Raison de l'événement (ex: 'Arrêt médical', 'Détachement', etc.)",
                        verbose_name="Motif / Détails",
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Événement de carrière",
                "verbose_name_plural": "Événements de carrière",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="FormationReglementaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom complet"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Identifiant unique"
                    ),
                ),
                (
                    "periodicite_ans",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Périodicité (ans)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentionLinguistique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "langue",
                    models.CharField(
                        choices=[("ANGLAIS", "Anglais"), ("FRANCAIS", "Français")],
                        max_length=20,
                    ),
                ),
                (
                    "niveau_oaci",
                    models.IntegerField(
                        choices=[(4, "Niveau 4"), (5, "Niveau 5"), (6, "Niveau 6")]
                    ),
                ),
                ("date_evaluation", models.DateField()),
                ("date_echeance", models.DateField()),
            ],
            options={
                "verbose_name": "Mention Linguistique",
                "verbose_name_plural": "Mentions Linguistiques",
            },
        ),
        migrations.CreateModel(
            name="MentionUniteAnnuelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_flux",
                    models.CharField(
                        choices=[("CAM", "CAM"), ("CAG", "CAG")], max_length=3
                    ),
                ),
                ("date_debut_cycle", models.DateField()),
                ("date_fin_cycle", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("SUSPENDU_INACTIVITE", "Suspendu (inactivité > 90j)"),
                            ("SUSPENDU_MANUEL", "Suspendu (décision manuelle)"),
                            (
                                "EN_ATTENTE_RENOUVELLEMENT",
                                "En attente de renouvellement",
                            ),
                            ("ARCHIVE", "Archivé (renouvelé ou muté)"),
                        ],
                        default="ACTIF",
                        max_length=30,
                    ),
                ),
                (
                    "annee_cycle",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Numéro de l'année dans le cycle de 3 ans pour le test triennal.",
                    ),
                ),
                (
                    "date_derniere_activite",
                    models.DateField(
                        blank=True,
                        help_text="Date du dernier vol enregistré pour cette MUA.",
                        null=True,
                    ),
                ),
                ("heures_cam_effectuees", models.FloatField(default=0.0)),
                ("heures_cag_acs_effectuees", models.FloatField(default=0.0)),
                ("heures_cag_aps_effectuees", models.FloatField(default=0.0)),
                ("heures_tour_effectuees", models.FloatField(default=0.0)),
                ("heures_en_cdq", models.FloatField(default=0.0)),
                ("heures_en_supervision", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Mention d'Unité Annuelle (MUA)",
                "verbose_name_plural": "Mentions d'Unité Annuelles (MUA)",
                "ordering": ["-date_debut_cycle"],
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_flux",
                    models.CharField(
                        choices=[
                            ("CAM", "CAM"),
                            ("CAG_ACS", "CAG - ACS"),
                            ("CAG_APS", "CAG - APS"),
                            ("TOUR", "Position TOUR"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "type_qualification",
                    models.CharField(
                        choices=[
                            ("CAER", "CAER"),
                            ("PC", "PC"),
                            ("CDQ", "Chef de Quart"),
                            ("ISP", "Instructeur sur Position"),
                            ("EXA", "Examinateur"),
                            ("ACS", "Contrôle d'Approche de Surveillance"),
                            ("APS", "Contrôle d'Approche de Précision"),
                            ("ADI", "Contrôle d'Aérodrome aux Instruments"),
                            ("ADV", "Contrôle d'Aérodrome à Vue"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_obtention", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("ARCHIVE_MUTATION", "Archivé (suite à mutation)"),
                        ],
                        default="ACTIF",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualification / Privilège",
                "verbose_name_plural": "Qualifications & Privilèges",
                "ordering": ["brevet", "centre", "date_obtention"],
            },
        ),
        migrations.CreateModel(
            name="RegleDeRenouvellement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_regle",
                    models.CharField(
                        help_text="Description claire de la règle (ex: 'Quota annuel CAM pour Istres')",
                        max_length=255,
                    ),
                ),
                (
                    "type_flux_mua",
                    models.CharField(
                        choices=[("CAM", "CAM"), ("CAG", "CAG")],
                        help_text="Type de MUA concernée par cette règle.",
                        max_length=3,
                    ),
                ),
                (
                    "source_heures_1",
                    models.CharField(
                        choices=[
                            ("heures_cam_effectuees", "Heures CAM"),
                            ("heures_cag_acs_effectuees", "Heures CAG ACS"),
                            ("heures_cag_aps_effectuees", "Heures CAG APS"),
                            ("heures_tour_effectuees", "Heures TOUR"),
                        ],
                        max_length=30,
                        verbose_name="Source principale d'heures",
                    ),
                ),
                (
                    "seuil_heures_1",
                    models.PositiveIntegerField(
                        verbose_name="Seuil requis pour la source principale"
                    ),
                ),
                (
                    "source_heures_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("heures_cam_effectuees", "Heures CAM"),
                            ("heures_cag_acs_effectuees", "Heures CAG ACS"),
                            ("heures_cag_aps_effectuees", "Heures CAG APS"),
                            ("heures_tour_effectuees", "Heures TOUR"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="Source secondaire d'heures (optionnel)",
                    ),
                ),
                (
                    "seuil_heures_2",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Seuil requis pour la source secondaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de renouvellement",
                "verbose_name_plural": "Règles de renouvellement",
            },
        ),
        migrations.CreateModel(
            name="SuiviFormationContinue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_formation",
                    models.CharField(
                        choices=[("PCU", "PCU"), ("FSAU", "FSAU")], max_length=4
                    ),
                ),
                ("date_realisation", models.DateField()),
            ],
            options={
                "verbose_name": "Suivi de Formation Continue",
                "verbose_name_plural": "Suivis de Formation Continue",
                "ordering": ["-date_realisation"],
            },
        ),
        migrations.CreateModel(
            name="SuiviFormationReglementaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_realisation", models.DateField()),
                ("date_echeance", models.DateField()),
            ],
        ),
    ]
