# Generated by Django 5.2.4 on 2025-08-18 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_alter_role_nom"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormationReglementaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                (
                    "periodicite_ans",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Périodicité (en années)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation Réglementaire",
                "verbose_name_plural": "Formations Réglementaires",
            },
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_licence",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="N° Licence / Brevet"
                    ),
                ),
                ("date_delivrance", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("VALIDE", "Valide"),
                            ("INAPTE_TEMP", "Inapte Temporaire"),
                            ("INAPTE_DEF", "Inapte Définitive"),
                            ("SUSPENDUE", "Suspendue"),
                        ],
                        default="VALIDE",
                        max_length=20,
                    ),
                ),
                (
                    "motif_inaptitude",
                    models.TextField(
                        blank=True,
                        help_text="Raison de l'inaptitude ou de la suspension.",
                        null=True,
                    ),
                ),
                ("date_debut_inaptitude", models.DateField(blank=True, null=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licence",
                        to="core.agent",
                    ),
                ),
                (
                    "certificat_medical",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.certificatmed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licence de contrôleur",
                "verbose_name_plural": "Licences des contrôleurs",
                "permissions": [
                    (
                        "view_all_licences",
                        "Peut voir les dossiers de compétences de tous les agents",
                    ),
                    (
                        "view_centre_licences",
                        "Peut voir les dossiers de compétences des agents de son centre",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_qualification",
                    models.CharField(
                        choices=[
                            ("ACS", "Contrôle d'Approche de Surveillance (ACS)"),
                            ("ADI", "Contrôle d'Aérodrome aux Instruments (ADI)"),
                            ("ADV", "Contrôle d'Aérodrome à Vue (ADV)"),
                            ("CAER", "CAER"),
                            ("PC", "PC"),
                            ("CDQ", "Chef de Quart"),
                            ("ISP", "Instructeur sur Position"),
                            ("EXA", "Examinateur"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_obtention", models.DateField()),
                (
                    "privileges_actifs",
                    models.BooleanField(
                        default=True,
                        help_text="Décocher si l'agent ne souhaite plus exercer les privilèges optionnels (ISP/EXA).",
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="competences.licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualification",
                "verbose_name_plural": "Qualifications",
                "unique_together": {("licence", "type_qualification")},
            },
        ),
        migrations.CreateModel(
            name="SuiviFormationReglementaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_realisation", models.DateField()),
                ("date_echeance", models.DateField()),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competences.formationreglementaire",
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formations_suivies",
                        to="competences.licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi de Formation Réglementaire",
                "verbose_name_plural": "Suivis des Formations Réglementaires",
            },
        ),
        migrations.CreateModel(
            name="MentionLinguistique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "langue",
                    models.CharField(
                        choices=[("ANGLAIS", "Anglais"), ("FRANCAIS", "Français")],
                        max_length=20,
                    ),
                ),
                (
                    "niveau_oaci",
                    models.IntegerField(
                        choices=[(4, "Niveau 4"), (5, "Niveau 5"), (6, "Niveau 6")]
                    ),
                ),
                ("date_evaluation", models.DateField()),
                ("date_echeance", models.DateField()),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions_linguistiques",
                        to="competences.licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mention Linguistique",
                "verbose_name_plural": "Mentions Linguistiques",
                "unique_together": {("licence", "langue")},
            },
        ),
        migrations.CreateModel(
            name="MentionUnite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_flux",
                    models.CharField(
                        choices=[
                            ("CAM", "Circulation Aérienne Militaire"),
                            ("CAG", "Circulation Aérienne Générale"),
                        ],
                        max_length=3,
                        verbose_name="Type de Mention",
                    ),
                ),
                (
                    "mention_particuliere",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Position/Secteur (ex: TOUR)",
                    ),
                ),
                ("date_delivrance", models.DateField()),
                (
                    "date_echeance",
                    models.DateField(verbose_name="Échéance de la mention"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE_MUTATION", "Inactive (suite à mutation)"),
                            ("EXPIREE", "Expirée"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "heures_requises_annuelles",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Heures requises/an"
                    ),
                ),
                (
                    "heures_effectuees_cycle",
                    models.FloatField(
                        default=0.0, verbose_name="Heures effectuées (cycle)"
                    ),
                ),
                ("date_debut_cycle", models.DateField()),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions_delivrees",
                        to="core.centre",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions_unite",
                        to="competences.qualification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mention d'Unité",
                "verbose_name_plural": "Mentions d'Unité",
                "unique_together": {("qualification", "centre", "type_flux")},
            },
        ),
    ]
