# Generated by Django 5.2.4 on 2025-08-20 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competences", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="brevet",
            name="agent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brevet",
                to="core.agent",
            ),
        ),
        migrations.AddField(
            model_name="evenementcarriere",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evenements_carriere",
                to="core.agent",
            ),
        ),
        migrations.AddField(
            model_name="evenementcarriere",
            name="cree_par",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mentionlinguistique",
            name="brevet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions_linguistiques",
                to="competences.brevet",
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="brevet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualifications",
                to="competences.brevet",
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="centre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualifications_delivrees",
                to="core.centre",
            ),
        ),
        migrations.AddField(
            model_name="mentionuniteannuelle",
            name="qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="muas",
                to="competences.qualification",
            ),
        ),
        migrations.AddField(
            model_name="reglederenouvellement",
            name="centre",
            field=models.ForeignKey(
                help_text="Centre auquel cette règle s'applique.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.centre",
            ),
        ),
        migrations.AddField(
            model_name="suiviformationcontinue",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formations_continues_suivies",
                to="core.agent",
            ),
        ),
        migrations.AddField(
            model_name="suiviformationreglementaire",
            name="brevet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formations_reglementaires_suivies",
                to="competences.brevet",
            ),
        ),
        migrations.AddField(
            model_name="suiviformationreglementaire",
            name="formation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="competences.formationreglementaire",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mentionlinguistique",
            unique_together={("brevet", "langue")},
        ),
        migrations.AlterUniqueTogether(
            name="qualification",
            unique_together={("brevet", "centre", "type_qualification")},
        ),
        migrations.AlterUniqueTogether(
            name="reglederenouvellement",
            unique_together={("centre", "type_flux_mua", "nom_regle")},
        ),
    ]
