# Generated by Django 5.2.4 on 2025-08-19 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competences", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="licence",
            name="agent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licence",
                to="core.agent",
            ),
        ),
        migrations.AddField(
            model_name="mentionlinguistique",
            name="licence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions_linguistiques",
                to="competences.licence",
            ),
        ),
        migrations.AddField(
            model_name="mentionunite",
            name="centre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions_delivrees",
                to="core.centre",
            ),
        ),
        migrations.AddField(
            model_name="mentionunite",
            name="licence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions_unite",
                to="competences.licence",
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="licence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualifications",
                to="competences.licence",
            ),
        ),
        migrations.AddField(
            model_name="mentionunite",
            name="qualification_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mentions_associees",
                to="competences.qualification",
            ),
        ),
        migrations.AddField(
            model_name="suiviformationreglementaire",
            name="formation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="competences.formationreglementaire",
            ),
        ),
        migrations.AddField(
            model_name="suiviformationreglementaire",
            name="licence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formations_suivies",
                to="competences.licence",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mentionlinguistique",
            unique_together={("licence", "langue")},
        ),
        migrations.AlterUniqueTogether(
            name="qualification",
            unique_together={("licence", "type_qualification")},
        ),
        migrations.AlterUniqueTogether(
            name="mentionunite",
            unique_together={
                ("licence", "centre", "type_flux", "mention_particuliere")
            },
        ),
    ]
