# Generated by Django 5.2.4 on 2025-08-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competences", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriqueCompetence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("STATUT_LICENCE", "Changement Statut Licence"),
                            ("MENTION_EXPIREE", "Mention d'Unité Expirée"),
                            ("FORMATION_ECHOUE", "Formation Réglementaire Échue"),
                            ("APTITUDE_MEDICALE_EXPIREE", "Aptitude Médicale Expirée"),
                            (
                                "APTITUDE_LINGUISTIQUE_EXPIREE",
                                "Aptitude Linguistique Expirée",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        help_text="Détails sur l'événement : quelle mention, quelle échéance, etc."
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="competences.licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de Compétence",
                "verbose_name_plural": "Historiques des Compétences",
                "ordering": ["-timestamp"],
            },
        ),
    ]
