# Generated by Django 5.2.4 on 2025-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competences", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentionuniteannuelle",
            name="heures_en_isp",
            field=models.FloatField(default=0.0, verbose_name="Heures en tant qu'ISP"),
        ),
    ]
