# Generated by Django 5.2.4 on 2025-08-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competences", "0003_historiquecompetence"),
    ]

    operations = [
        migrations.AddField(
            model_name="formationreglementaire",
            name="slug",
            field=models.SlugField(
                default="fh-raf-aero-temp",
                help_text="Identifiant court utilisé par le système, ex: 'fh-raf-aero'. Ne doit pas être changé une fois créé.",
                max_length=100,
                unique=True,
                verbose_name="Identifiant unique (ne pas modifier)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formationreglementaire",
            name="nom",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Nom complet de la formation"
            ),
        ),
    ]
