# Generated by Django 5.2.4 on 2025-08-19 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("BUG", "Anomalie / Bug"),
                            ("AMELIORATION", "Suggestion d'amélioration"),
                            ("QUESTION", "Question"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module_concerne",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Général / Authentification"),
                            ("PLANNING", "Tour de Service (Planning)"),
                            ("FEUILLE_TEMPS", "Feuille de Temps"),
                            ("CAHIER_DE_MARCHE", "Cahier de Marche"),
                            ("DOCUMENTATION", "Documentation"),
                            ("TECHNIQUE", "Technique (Pannes & MISO)"),
                            ("QS", "Sécurité Aérienne (QS)"),
                            ("ES", "Études de Sécurité (ES)"),
                            ("CYBER", "Cybersécurité (SMSI)"),
                            ("SUIVI", "Suivi des Actions"),
                            ("FEEDBACK", "Module de Feedback"),
                        ],
                        max_length=30,
                        verbose_name="Module Concerné",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedbacks_soumis",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retour Utilisateur",
                "verbose_name_plural": "Retours Utilisateurs",
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "view_feedback_dashboard",
                        "Peut voir le tableau de bord des feedbacks",
                    )
                ],
            },
        ),
    ]
