# Generated by Django 5.2.4 on 2025-08-14 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Miso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_debut",
                    models.DateTimeField(verbose_name="Date et heure de début"),
                ),
                ("date_fin", models.DateTimeField(verbose_name="Date et heure de fin")),
                (
                    "type_maintenance",
                    models.CharField(
                        choices=[
                            ("RADIO", "Radio"),
                            ("RADAR", "Radar"),
                            ("VISU", "Visualisation"),
                            ("INFRA", "Infrastructure"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de maintenance",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de l'intervention"),
                ),
                (
                    "piece_jointe",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="miso_attachments/%Y/%m/",
                        verbose_name="Pièce jointe",
                    ),
                ),
                (
                    "statut_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ANNULE", "Annulé"),
                            ("PLANIFIE", "Planifié"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Statut manuel (Annulé)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="misos",
                        to="core.centre",
                        verbose_name="Centre concerné",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="misos_crees",
                        to="core.agent",
                        verbose_name="Responsable ES",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préavis de Maintenance (MISO)",
                "verbose_name_plural": "Préavis de Maintenance (MISO)",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="MisoHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création du préavis"),
                            ("MODIFICATION", "Modification des détails"),
                            ("ANNULATION", "Annulation du préavis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Détails de l'événement au format JSON (ex: motif d'annulation)",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur de l'événement",
                    ),
                ),
                (
                    "miso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="technique.miso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique MISO",
                "verbose_name_plural": "Historiques MISO",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PanneCentre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_equipement",
                    models.CharField(
                        choices=[
                            ("RADIO", "Radio"),
                            ("RADAR", "Radar"),
                            ("VISU", "Visualisation"),
                            ("TELEPHONIE", "Telephone"),
                            ("INTERPHONIE", "Interphone"),
                            ("INFRA", "Infrastructure"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=30,
                        verbose_name="Système concerné",
                    ),
                ),
                (
                    "equipement_details",
                    models.CharField(
                        blank=True,
                        help_text="Nom ou référence exacte de l'équipement en panne.",
                        max_length=255,
                        verbose_name="Précisions sur l'équipement",
                    ),
                ),
                (
                    "date_heure_debut",
                    models.DateTimeField(
                        db_index=True, help_text="Date et heure du début de la panne."
                    ),
                ),
                (
                    "date_heure_fin",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure de la résolution de la panne (laisser vide si en cours).",
                        null=True,
                    ),
                ),
                (
                    "criticite",
                    models.CharField(
                        choices=[
                            ("CRITIQUE", "Critique (impact opérationnel direct)"),
                            ("MAJEURE", "Majeure (dégradation notable)"),
                            ("MINEURE", "Mineure (gêne ou problème de confort)"),
                        ],
                        default="MINEURE",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description de la panne et de son impact."
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("EN_COURS", "En cours"), ("RESOLUE", "Résolue")],
                        default="EN_COURS",
                        max_length=20,
                    ),
                ),
                (
                    "notification_generale",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez cette case si cette panne doit faire l'objet d'une notification.",
                        verbose_name="Signaler pour notification générale",
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pannes_consignees",
                        to="core.agent",
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pannes",
                        to="core.centre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Panne Centre",
                "verbose_name_plural": "Pannes Centre",
                "ordering": ["-date_heure_debut"],
                "permissions": [
                    ("resolve_pannecentre", "Peut marquer une panne comme résolue")
                ],
            },
        ),
        migrations.CreateModel(
            name="PanneHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création de la panne"),
                            ("MODIFICATION", "Modification des détails"),
                            ("RESOLUTION", "Résolution de la panne"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Détails de l'événement (ex: commentaire, changements)",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur de l'événement",
                    ),
                ),
                (
                    "panne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="technique.pannecentre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de Panne",
                "verbose_name_plural": "Historiques des Pannes",
                "ordering": ["-timestamp"],
            },
        ),
    ]
