# Generated by Django 5.2.4 on 2025-08-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technique", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MisoHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création du préavis"),
                            ("MODIFICATION", "Modification des détails"),
                            ("ANNULATION", "Annulation du préavis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Détails de l'événement au format JSON (ex: motif d'annulation)",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur de l'événement",
                    ),
                ),
                (
                    "miso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="technique.miso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique MISO",
                "verbose_name_plural": "Historiques MISO",
                "ordering": ["-timestamp"],
            },
        ),
    ]
