# Generated by Django 5.2.4 on 2025-08-09 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technique", "0002_misohistorique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pannecentre",
            name="equipement_concerne",
        ),
        migrations.AddField(
            model_name="pannecentre",
            name="equipement_details",
            field=models.CharField(
                blank=True,
                help_text="Nom ou référence exacte de l'équipement en panne.",
                max_length=255,
                verbose_name="Précisions sur l'équipement",
            ),
        ),
        migrations.AddField(
            model_name="pannecentre",
            name="type_equipement",
            field=models.CharField(
                choices=[
                    ("RADIO", "Radio"),
                    ("RADAR", "Radar"),
                    ("VISU", "Visualisation"),
                    ("TELEPHONIE", "Telephone"),
                    ("INTERPHONIE", "Interphone"),
                    ("INFRA", "Infrastructure"),
                    ("AUTRE", "Autre"),
                ],
                default="AUTRE",
                max_length=30,
                verbose_name="Système concerné",
            ),
        ),
        migrations.CreateModel(
            name="PanneHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création de la panne"),
                            ("MODIFICATION", "Modification des détails"),
                            ("RESOLUTION", "Résolution de la panne"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Détails de l'événement (ex: commentaire, changements)",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur de l'événement",
                    ),
                ),
                (
                    "panne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="technique.pannecentre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de Panne",
                "verbose_name_plural": "Historiques des Pannes",
                "ordering": ["-timestamp"],
            },
        ),
    ]
