# Generated by Django 5.2.4 on 2025-08-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Changement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=255, verbose_name="Titre / Objet du changement"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description sommaire du besoin"),
                ),
                (
                    "fichier_notification_initiale",
                    models.FileField(
                        upload_to="es/notifications/%Y/%m/",
                        verbose_name="Fichier de Notification (Annexe 1)",
                    ),
                ),
                (
                    "fichier_reponse_notification",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="es/reponses/%Y/%m/",
                        verbose_name="Fichier de Réponse (Annexe 2)",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("NON_DEFINI", "Non Défini"),
                            ("SUIVI", "Suivi"),
                            ("NON_SUIVI", "Non Suivi"),
                        ],
                        default="NON_DEFINI",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NOTIFICATION", "En attente de classification"),
                            ("ETUDE_REQUISE", "Étude de sécurité requise"),
                            ("REALISATION", "Réalisation"),
                            ("CLOS", "Clos"),
                        ],
                        default="NOTIFICATION",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "centre_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changements_pilotes",
                        to="core.centre",
                        verbose_name="Centre pilote",
                    ),
                ),
                (
                    "correspondant_dircam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changements_supervises",
                        to="core.agent",
                        verbose_name="Correspondant (ES National)",
                    ),
                ),
                (
                    "initiateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changements_inities",
                        to="core.agent",
                        verbose_name="Initiateur (ES Local)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processus de Changement",
                "verbose_name_plural": "Processus de Changements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EtudeSecurite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_etude",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence de l'étude"
                    ),
                ),
                (
                    "plan_securite_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="es/plans_securite/%Y/%m/",
                        verbose_name="Plan de Sécurité (Annexe 4)",
                    ),
                ),
                (
                    "fichier_approbation_finale",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="es/approbations/%Y/%m/",
                        verbose_name="Décision d'Approbation Finale (Annexe 5)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("INITIALISATION", "Initialisation"),
                            ("INSTRUCTION_COURS", "Instruction en cours"),
                            ("VALIDATION_FINALE", "En attente de validation finale"),
                            ("CLOTUREE", "Clôturée"),
                        ],
                        default="INITIALISATION",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etude_securite",
                        to="es.changement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étude de Sécurité",
                "verbose_name_plural": "Études de Sécurité",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentaireEtude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("commentaire", models.TextField()),
                (
                    "piece_jointe",
                    models.FileField(
                        blank=True, null=True, upload_to="es/commentaires_pj/%Y/%m/"
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.agent"
                    ),
                ),
                (
                    "etude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to="es.etudesecurite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire d'Étude",
                "verbose_name_plural": "Commentaires d'Étude",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EtapeEtude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("PREPA", "Phase Préparatoire"),
                            ("FHA", "Analyse des Dangers Fonctionnels (FHA)"),
                            ("PSSA", "Analyse Préliminaire de Sécurité (PSSA)"),
                            ("SSA", "Analyse de Sécurité du Système (SSA)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "document_preuve",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="es/preuves/%Y/%m/",
                        verbose_name="Document de Preuve",
                    ),
                ),
                (
                    "mrr_identifies",
                    models.TextField(
                        blank=True,
                        help_text="Un MRR par ligne. Ces MRR généreront des actions de suivi lors de la validation nationale.",
                        verbose_name="MRR identifiés à cette étape",
                    ),
                ),
                (
                    "validee_par_local",
                    models.BooleanField(
                        default=False, verbose_name="Validée par ES Local"
                    ),
                ),
                ("date_validation_local", models.DateTimeField(blank=True, null=True)),
                (
                    "validee_par_national",
                    models.BooleanField(
                        default=False, verbose_name="Validée par ES National"
                    ),
                ),
                (
                    "date_validation_national",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "etude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapes",
                        to="es.etudesecurite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape d'Étude de Sécurité",
                "verbose_name_plural": "Étapes des Études de Sécurité",
                "ordering": ["etude", "id"],
                "unique_together": {("etude", "nom")},
            },
        ),
    ]
