# Generated by Django 5.2.4 on 2025-08-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("es", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudesecurite",
            name="type_etude",
            field=models.CharField(
                choices=[
                    ("DOSSIER_SECURITE", "Dossier de Sécurité (Complet)"),
                    ("EPIS", "Étude Prestataire d’Impact sur la Sécurité (EPIS)"),
                    ("DSSL", "Démonstration de Sécurité Simplifiée Locale (DSSL)"),
                ],
                default="DOSSIER_SECURITE",
                max_length=20,
            ),
        ),
    ]
