# Generated by Django 5.2.4 on 2025-08-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("es", "0002_etudesecurite_type_etude"),
    ]

    operations = [
        migrations.CreateModel(
            name="MRR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description du MRR")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.agent"
                    ),
                ),
                (
                    "etude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mrrs",
                        to="es.etudesecurite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moyen en Réduction de Risque (MRR)",
                "verbose_name_plural": "Moyens en Réduction de Risque (MRR)",
                "ordering": ["-created_at"],
            },
        ),
    ]
