# Generated by Django 5.2.4 on 2025-08-15 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("es", "0003_mrr"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudesecurite",
            name="avancement",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Avancement",
            ),
        ),
    ]
