# Generated by Django 5.2.4 on 2025-07-30 18:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Type de Document",
                "verbose_name_plural": "Types de Documents",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.CharField(max_length=255, verbose_name="Intitulé")),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Objet du document"),
                ),
                (
                    "statut_suivi",
                    models.CharField(
                        choices=[
                            ("A_JOUR", "À jour"),
                            ("RENOUVELLEMENT_PLANIFIE", "Renouvellement planifié"),
                            ("EN_REDACTION", "En rédaction (Nouvelle version)"),
                            ("PERIME", "Périmé (Action requise)"),
                            ("ARCHIVE", "Archivé"),
                        ],
                        default="A_JOUR",
                        max_length=30,
                    ),
                ),
                (
                    "date_echeance_suivi",
                    models.DateField(
                        verbose_name="Prochaine échéance (relecture/remplacement)"
                    ),
                ),
                (
                    "centres_applicables",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documentation_applicable",
                        to="core.centre",
                    ),
                ),
                (
                    "responsable_suivi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents_supervises",
                        to="core.agent",
                        verbose_name="Responsable du suivi",
                    ),
                ),
                (
                    "type_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documentation.documenttype",
                        verbose_name="Type de document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche Document",
                "verbose_name_plural": "Fiches Document",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="VersionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_version", models.CharField(max_length=20)),
                (
                    "fichier_pdf",
                    models.FileField(
                        help_text="Le fichier PDF finalisé",
                        upload_to="documentation/%Y/%m/",
                    ),
                ),
                (
                    "date_mise_en_vigueur",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_VIGUEUR", "En vigueur"),
                            ("REMPLACEE", "Remplacée"),
                            ("ARCHIVEE", "Archivée"),
                        ],
                        default="EN_VIGUEUR",
                        max_length=20,
                    ),
                ),
                (
                    "commentaire_version",
                    models.TextField(blank=True, help_text="Résumé des modifications"),
                ),
                ("enregistre_le", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documentation.document",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Version de Document",
                "verbose_name_plural": "Versions de Document",
                "ordering": ["-date_mise_en_vigueur"],
                "unique_together": {("document", "numero_version")},
            },
        ),
        migrations.CreateModel(
            name="Relecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_realisation",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "decision",
                    models.CharField(
                        help_text="Ex: 'Document reconduit sans modification'",
                        max_length=255,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_relectures",
                        to="documentation.document",
                    ),
                ),
                (
                    "realisee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.agent"
                    ),
                ),
                (
                    "version_concernee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documentation.versiondocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de Relecture",
                "verbose_name_plural": "Historiques de Relecture",
                "ordering": ["-date_realisation"],
            },
        ),
    ]
