# Generated by Django 5.2.4 on 2025-08-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Type de Document",
                "verbose_name_plural": "Types de Documents",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("intitule", models.CharField(max_length=255, verbose_name="Intitulé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Objet du document"),
                ),
                (
                    "fichier_pdf",
                    models.FileField(
                        help_text="Le fichier PDF associé à ce document.",
                        upload_to="documentation/%Y/%m/",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_REDACTION", "En Rédaction"),
                            ("EN_VIGUEUR", "En Vigueur"),
                            ("REMPLACE", "Remplacé"),
                            ("ARCHIVE", "Archivé"),
                        ],
                        default="EN_REDACTION",
                        max_length=20,
                    ),
                ),
                (
                    "date_mise_en_vigueur",
                    models.DateField(
                        blank=True,
                        help_text="Date à partir de laquelle le document est applicable.",
                        null=True,
                    ),
                ),
                (
                    "periodicite_relecture_mois",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Ex: 12 pour une relecture annuelle.",
                        verbose_name="Périodicité de relecture (en mois)",
                    ),
                ),
                (
                    "date_prochaine_echeance",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Prochaine échéance de relecture",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "centres_applicables",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documentation_applicable",
                        to="core.centre",
                    ),
                ),
                (
                    "document_parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Le document principal auquel cet avenant est rattaché.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avenants",
                        to="documentation.document",
                    ),
                ),
                (
                    "remplace_document",
                    models.OneToOneField(
                        blank=True,
                        help_text="Le document que cette version remplace.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remplace_par",
                        to="documentation.document",
                    ),
                ),
                (
                    "responsable_suivi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents_supervises",
                        to="core.agent",
                        verbose_name="Responsable du suivi",
                    ),
                ),
                (
                    "type_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documentation.documenttype",
                        verbose_name="Type de document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentPriseEnCompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Date et heure de la prise en compte",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents_pris_en_compte",
                        to="core.agent",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prises_en_compte",
                        to="documentation.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prise en Compte de Document",
                "verbose_name_plural": "Prises en Compte de Documents",
                "ordering": ["timestamp"],
                "unique_together": {("document", "agent")},
            },
        ),
    ]
