# Generated by Django 5.2.4 on 2025-08-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("documentation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPriseEnCompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Date et heure de la prise en compte",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents_pris_en_compte",
                        to="core.agent",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prises_en_compte",
                        to="documentation.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prise en Compte de Document",
                "verbose_name_plural": "Prises en Compte de Documents",
                "ordering": ["timestamp"],
                "unique_together": {("document", "agent")},
            },
        ),
    ]
