# Generated by Django 5.2.4 on 2025-08-01 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("documentation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="date_echeance_suivi",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prochaine échéance (relecture/remplacement)",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="responsable_suivi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents_supervises",
                to="core.agent",
                verbose_name="Responsable du suivi",
            ),
        ),
    ]
