# Generated by Django 5.2.4 on 2025-08-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentation", "0002_alter_document_date_echeance_suivi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="versiondocument",
            name="statut_diffusion",
            field=models.CharField(
                choices=[
                    ("A_DIFFUSER", "Prêt pour diffusion"),
                    ("DIFFUSION_LANCEE", "Diffusion lancée"),
                    ("ACTION_CLOTUREE", "Action clôturée"),
                ],
                default="A_DIFFUSER",
                max_length=20,
            ),
        ),
    ]
