# Generated by Django 5.2.4 on 2025-08-21 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SaisieActivite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CONTROLEUR", "Contrôleur en Charge"),
                            ("STAGIAIRE", "Contrôleur Stagiaire"),
                            ("ISP", "Instructeur sur Position (ISP)"),
                            ("CDQ", "Chef de Quart (CDQ)"),
                            ("SUPERVISEUR", "Superviseur"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saisie d'activité",
                "verbose_name_plural": "Saisies d'activité",
            },
        ),
        migrations.CreateModel(
            name="Vol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_strip", models.CharField(blank=True, max_length=50)),
                ("numero_commande", models.CharField(blank=True, max_length=100)),
                ("date_vol", models.DateField()),
                (
                    "heure_debut_prevue",
                    models.TimeField(verbose_name="Heure de début prévue"),
                ),
                (
                    "duree_prevue",
                    models.DurationField(
                        default=datetime.timedelta(0),
                        help_text="Format: HH:MM:SS",
                        verbose_name="Durée prévue",
                    ),
                ),
                (
                    "indicatif",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Indicatif du vol"
                    ),
                ),
                (
                    "flux",
                    models.CharField(
                        choices=[
                            ("CAM", "CAM"),
                            ("CAG_ACS", "CAG - ACS"),
                            ("CAG_APS", "CAG - APS"),
                            ("TOUR", "Position TOUR"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "heure_debut_reelle",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de début réelle"
                    ),
                ),
                (
                    "heure_fin_reelle",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin réelle"
                    ),
                ),
            ],
        ),
    ]
