# Generated by Django 5.2.4 on 2025-08-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SaisieActivite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CONTROLEUR", "Contrôleur en Charge"),
                            ("STAGIAIRE", "Contrôleur Stagiaire"),
                            ("ISP", "Instructeur sur Position (ISP)"),
                            ("CDQ", "Chef de Quart (CDQ)"),
                            ("SUPERVISEUR", "Superviseur"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saisie d'activité",
                "verbose_name_plural": "Saisies d'activité",
            },
        ),
        migrations.CreateModel(
            name="Vol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_vol", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                (
                    "flux",
                    models.CharField(
                        choices=[
                            ("CAM", "CAM"),
                            ("CAG_ACS", "CAG - ACS"),
                            ("CAG_APS", "CAG - APS"),
                            ("TOUR", "Position TOUR"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "indicatif",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Indicatif du vol"
                    ),
                ),
            ],
        ),
    ]
