# Generated by Django 5.2.4 on 2025-08-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activites", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saisieactivite",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activites",
                to="core.agent",
            ),
        ),
        migrations.AddField(
            model_name="vol",
            name="centre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vols",
                to="core.centre",
            ),
        ),
        migrations.AddField(
            model_name="vol",
            name="parent_vol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="releves",
                to="activites.vol",
                verbose_name="Vol d'origine (mission)",
            ),
        ),
        migrations.AddField(
            model_name="saisieactivite",
            name="vol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activites",
                to="activites.vol",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saisieactivite",
            unique_together={("vol", "agent")},
        ),
    ]
