# Generated by Django 5.2.4 on 2025-09-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activites", "0002_initial"),
        ("core", "0002_typeactivitehorsvol_centre_sous_gestion_cca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vol",
            name="est_activite_hors_vol",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vol",
            name="nom_cabine",
            field=models.CharField(
                blank=True,
                help_text="Nom de la cabine/position assignée par la CCA ou le Planificateur Local.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="vol",
            name="statut",
            field=models.CharField(
                choices=[
                    ("DEMANDE", "Demandé"),
                    ("PLANIFIE", "Planifié"),
                    ("ASSIGNE", "Assigné"),
                    ("TERMINE", "Terminé"),
                    ("CONSOLIDE", "Consolidé"),
                    ("ANNULE", "Annulé"),
                ],
                default="DEMANDE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vol",
            name="type_activite_hors_vol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.typeactivitehorsvol",
            ),
        ),
    ]
