# Generated by Django 5.2.4 on 2025-08-20 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_action",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("FONCTIONNEMENT", "Fonctionnement"),
                            ("DIFFUSION_DOC", "Diffusion Documentaire"),
                            ("RECOMMANDATION_QS", "Recommandation QS"),
                            ("PRISE_EN_COMPTE_DOC", "Prise en Compte Documentaire"),
                            ("AUDIT", "Audit"),
                            ("ETUDE_SECURITE", "Étude de Sécurité"),
                            ("INSTRUCTION_FNE", "Instruction FNE (QS)"),
                            ("RELECTURE_DOC", "Relecture Documentaire"),
                            ("VALIDATION_AVENANT", "Validation d'Avenant"),
                            ("SUIVI_MRR", "Suivi de MRR"),
                            ("TRAITEMENT_RISQUE_CYBER", "Traitement de Risque Cyber"),
                            (
                                "REMEDIATION_INCIDENT_CYBER",
                                "Remédiation d'Incident Cyber",
                            ),
                            ("FEEDBACK_UTILISATEUR", "Feedback Utilisateur"),
                            ("TRAITEMENT_FEEDBACK", "Traitement Retour Utilisateur"),
                        ],
                        default="FONCTIONNEMENT",
                        max_length=30,
                    ),
                ),
                ("echeance", models.DateField()),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("BASSE", "Basse"),
                            ("MOYENNE", "Moyenne"),
                            ("HAUTE", "Haute"),
                        ],
                        default="MOYENNE",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A_FAIRE", "À faire"),
                            ("EN_COURS", "En cours"),
                            ("A_VALIDER", "À valider"),
                            ("VALIDEE", "Validée / Clôturée"),
                            ("REFUSEE", "Refusée"),
                            ("ARCHIVEE", "Archivée"),
                        ],
                        default="A_FAIRE",
                        max_length=20,
                    ),
                ),
                ("avancement", models.IntegerField(default=0)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("echeance_proposee", models.DateField(blank=True, null=True)),
                (
                    "centres",
                    models.ManyToManyField(
                        blank=True,
                        related_name="actions",
                        to="core.centre",
                        verbose_name="Centres Concernés",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_taches",
                        to="suivi.action",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions_a_realiser",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["echeance", "priorite"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création"),
                            ("CHANGEMENT_STATUT", "Changement de statut"),
                            ("CHANGEMENT_AVANCEMENT", "Changement d'avancement"),
                            ("COMMENTAIRE", "Commentaire ajouté"),
                            (
                                "DEMANDE_REAJUSTEMENT",
                                "Demande de réajustement d'échéance",
                            ),
                            ("APPROBATION_REAJUSTEMENT", "Approbation de réajustement"),
                            ("REFUS_REAJUSTEMENT", "Refus de réajustement"),
                            ("CHANGEMENT_RESPONSABLE", "Changement de responsable"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Détails de l'événement au format JSON (ex: {'ancienne_valeur': 'EN_COURS', 'nouvelle_valeur': 'A_VALIDER'})",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="suivi.action",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur de l'événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'Action",
                "verbose_name_plural": "Historiques des Actions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PriseEnCompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action_agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prise_en_compte",
                        to="suivi.action",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.agent"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prise en compte par l'agent",
                "verbose_name_plural": "Prises en compte par les agents",
            },
        ),
    ]
