# Generated by Django 5.2.4 on 2025-07-30 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_action",
                    models.CharField(
                        blank=True,
                        help_text="Ex: ACT-2025-001. Peut être généré automatiquement.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=255, verbose_name="Titre / Libellé de l'action"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        verbose_name="Description détaillée / Livrables attendus",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A_FAIRE", "À faire"),
                            ("EN_COURS", "En cours"),
                            ("A_VALIDER", "À valider"),
                            ("REFUSEE", "Refusée"),
                            ("VALIDEE", "Validée / Clôturée"),
                            ("ARCHIVEE", "Archivée"),
                        ],
                        default="A_FAIRE",
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("BASSE", "Basse"),
                            ("MOYENNE", "Moyenne"),
                            ("HAUTE", "Haute"),
                        ],
                        default="MOYENNE",
                        max_length=20,
                    ),
                ),
                (
                    "avancement",
                    models.IntegerField(
                        default=0, help_text="Pourcentage de réalisation (0-100)"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("echeance", models.DateField(verbose_name="Échéance initiale")),
                (
                    "date_cloture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de clôture effective"
                    ),
                ),
                (
                    "statut_echeance",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("DEMANDE_EN_COURS", "Demande de réajustement en cours"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "echeance_proposee",
                    models.DateField(
                        blank=True, null=True, verbose_name="Nouvelle échéance proposée"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="L'ID de l'objet à l'origine de l'action"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Le type de modèle à l'origine de l'action (ex: Document, EvenementQS)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_taches",
                        to="suivi.action",
                        verbose_name="Tâche parente (Maître)",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions_a_realiser",
                        to="core.agent",
                        verbose_name="Responsable de la réalisation",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions_a_valider",
                        to="core.agent",
                        verbose_name="Validateur de la clôture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action de Suivi",
                "verbose_name_plural": "Actions de Suivi",
                "ordering": ["echeance", "priorite"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création"),
                            ("CHANGEMENT_STATUT", "Changement de statut"),
                            ("CHANGEMENT_AVANCEMENT", "Changement d'avancement"),
                            ("COMMENTAIRE", "Commentaire ajouté"),
                            (
                                "DEMANDE_REAJUSTEMENT",
                                "Demande de réajustement d'échéance",
                            ),
                            ("APPROBATION_REAJUSTEMENT", "Approbation de réajustement"),
                            ("REFUS_REAJUSTEMENT", "Refus de réajustement"),
                            ("CHANGEMENT_RESPONSABLE", "Changement de responsable"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Détails de l'événement au format JSON (ex: {'ancienne_valeur': 'EN_COURS', 'nouvelle_valeur': 'A_VALIDER'})",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="suivi.action",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur de l'événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'Action",
                "verbose_name_plural": "Historiques des Actions",
                "ordering": ["-timestamp"],
            },
        ),
    ]
