# Generated by Django 5.2.4 on 2025-08-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("FONCTIONNEMENT", "Fonctionnement"),
                    ("DIFFUSION_DOC", "Diffusion Documentaire"),
                    ("RECOMMANDATION_QS", "Recommandation QS"),
                    ("PRISE_EN_COMPTE_DOC", "Prise en Compte Documentaire"),
                    ("AUDIT", "Audit"),
                    ("ETUDE_SECURITE", "Étude de Sécurité"),
                ],
                default="FONCTIONNEMENT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="statut",
            field=models.CharField(
                choices=[
                    ("A_FAIRE", "À faire"),
                    ("EN_COURS", "En cours"),
                    ("A_VALIDER", "À valider"),
                    ("VALIDEE", "Validée / Clôturée"),
                    ("REFUSEE", "Refusée"),
                    ("ARCHIVEE", "Archivée"),
                ],
                default="A_FAIRE",
                max_length=20,
            ),
        ),
    ]
