# Generated by Django 5.2.4 on 2025-08-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("FONCTIONNEMENT", "Fonctionnement"),
                    ("DIFFUSION_DOC", "Diffusion Documentaire"),
                    ("RECOMMANDATION_QS", "Recommandation QS"),
                    ("PRISE_EN_COMPTE_DOC", "Prise en Compte Documentaire"),
                    ("AUDIT", "Audit"),
                    ("ETUDE_SECURITE", "Étude de Sécurité"),
                    ("INSTRUCTION_FNE", "Instruction FNE (QS)"),
                    ("RELECTURE_DOC", "Relecture Documentaire"),
                    ("VALIDATION_AVENANT", "Validation d'Avenant"),
                    ("SUIVI_MRR", "Suivi de MRR"),
                ],
                default="FONCTIONNEMENT",
                max_length=30,
            ),
        ),
    ]
