# Generated by Django 5.2.4 on 2025-08-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi", "0003_alter_action_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("FONCTIONNEMENT", "Fonctionnement"),
                    ("DIFFUSION_DOC", "Diffusion Documentaire"),
                    ("RECOMMANDATION_QS", "Recommandation QS"),
                    ("PRISE_EN_COMPTE_DOC", "Prise en Compte Documentaire"),
                    ("AUDIT", "Audit"),
                    ("ETUDE_SECURITE", "Étude de Sécurité"),
                    ("INSTRUCTION_FNE", "Instruction FNE (QS)"),
                    ("RELECTURE_DOC", "Relecture Documentaire"),
                    ("VALIDATION_AVENANT", "Validation d'Avenant"),
                    ("SUIVI_MRR", "Suivi de MRR"),
                    ("TRAITEMENT_RISQUE_CYBER", "Traitement de Risque Cyber"),
                    ("REMEDIATION_INCIDENT_CYBER", "Remédiation d'Incident Cyber"),
                    ("FEEDBACK_UTILISATEUR", "Feedback Utilisateur"),
                ],
                default="FONCTIONNEMENT",
                max_length=30,
            ),
        ),
    ]
